-- Create databases for services
CREATE DATABASE IF NOT EXISTS dify;
CREATE DATABASE IF NOT EXISTS n8n;
CREATE DATABASE IF NOT EXISTS litellm;

-- Create users
CREATE USER IF NOT EXISTS dify_user WITH ENCRYPTED PASSWORD 'dify_password';
CREATE USER IF NOT EXISTS n8n_user WITH ENCRYPTED PASSWORD 'n8n_password';
CREATE USER IF NOT EXISTS litellm_user WITH ENCRYPTED PASSWORD 'litellm_password';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE dify TO dify_user;
GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n_user;
GRANT ALL PRIVILEGES ON DATABASE litellm TO litellm_user;
