#!/usr/bin/env bash
# =============================================================================
# Script 1: Setup Tenant - v2.3.0 (FINAL, README COMPLIANT)
# =============================================================================
# PURPOSE: Fully prepares a tenant environment in 100% compliance with README.md
#        - Pre-creates ALL directories to prevent root-owned volume mounts.
#        - Enforces tenant ownership across ALL directories.
#        - Generates a complete .env file and a VALID Caddyfile.
# USAGE:   sudo bash scripts/1-setup-system.sh <tenant_id> <domain>
# =============================================================================

set -euo pipefail

# --- Arguments & Colors ---
if [[ "${#@}" -ne 2 ]]; then echo "Usage: sudo bash $0 <tenant_id> <domain>" >&2; exit 1; fi
TENANT_ID="$1"
DOMAIN="$2"
RED='\033[0;31m' GREEN='\033[0;32m' CYAN='\033[0;36m' NC='\033[0m'
log() { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok() { echo -e "${GREEN}[OK]${NC}    $*"; }
fail() { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# --- Paths and User Info ---
TENANT_DIR="/mnt/data/${TENANT_ID}"
TENANT_USER="${TENANT_ID}"

# --- Pre-flight Checks ---
if [[ -d "${TENANT_DIR}" ]]; then fail "Tenant directory '${TENANT_DIR}' already exists."; fi
if ! id "${TENANT_USER}" &>/dev/null; then fail "User '${TENANT_USER}' does not exist."; fi
TENANT_UID=$(id -u "${TENANT_USER}")
TENANT_GID=$(id -g "${TENANT_USER}")
ok "Tenant user '${TENANT_USER}' (UID: ${TENANT_UID}, GID: ${TENANT_GID}) will own all resources."

# =============================================================================
# STEP 1: PRE-CREATE ALL DIRECTORIES (THE GRAFANA FIX)
# =============================================================================
log "Creating all service directories for tenant '${TENANT_ID}'..."
# This list must be exhaustive to prevent Docker from creating a directory as root.
DIRECTORIES=(
    "logs" "caddy-data" "caddy" "postgres" "redis" "qdrant" "ollama" "openwebui" 
    "n8n" "n8n/workflows" "flowise" "anythingllm/tmp" "litellm" "authentik/media" 
    "authentik/custom-templates" "prometheus-data" "grafana/provisioning/datasources"
    "grafana/provisioning/dashboards"
)
for dir in "${DIRECTORIES[@]}"; do
    mkdir -p "${TENANT_DIR}/${dir}"
    ok "Created directory: ${TENANT_DIR}/${dir}"
done

# =============================================================================
# STEP 2: ENFORCE TENANT OWNERSHIP (THE 'NOTHING AS ROOT' FIX)
# =============================================================================
log "Setting ownership for ALL directories to ${TENANT_UID}:${TENANT_GID}..."
chown -R "${TENANT_UID}:${TENANT_GID}" "${TENANT_DIR}"
ok "Ownership is now fully compliant with the non-root principle."

# =============================================================================
# STEP 3: GENERATE CONFIGURATION FILES
# =============================================================================
log "Generating Caddyfile..."
CADDYFILE_PATH="${TENANT_DIR}/caddy/Caddyfile"
cat > "${CADDYFILE_PATH}" << EOF
# Auto-generated Caddyfile for ${TENANT_ID} from script-1 (v2.3.0)
{
    acme_dns cloudflare {env.CF_API_TOKEN}
    email {env.ACME_EMAIL}
}

n8n.${DOMAIN} {
    reverse_proxy n8n:5678
}
flowise.${DOMAIN} {
    reverse_proxy flowise:3000
}
openwebui.${DOMAIN} {
    reverse_proxy openwebui:8080
}
anythingllm.${DOMAIN} {
    reverse_proxy anythingllm:8888
}
grafana.${DOMAIN} {
    reverse_proxy grafana:3000
}
litellm.${DOMAIN} {
    reverse_proxy litellm:4000
}
auth.${DOMAIN} {
    reverse_proxy authentik-server:9000
}
EOF
ok "Generated valid Caddyfile at ${CADDYFILE_PATH}"

log "Generating prometheus.yml..."
PROMETHEUS_PATH="${TENANT_DIR}/prometheus.yml"
cat > "${PROMETHEUS_PATH}" << EOF
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
EOF
ok "Generated prometheus.yml at ${PROMETHEUS_PATH}"

log "Generating complete .env file..."
ENV_FILE_PATH="${TENANT_DIR}/.env"

# Generate secrets
POSTGRES_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 16)
GRAFANA_PASSWORD=$(openssl rand -hex 16)
AUTHENTIK_SECRET_KEY=$(openssl rand -hex 16)
QDRANT_API_KEY=$(openssl rand -hex 16)
LITELLM_MASTER_KEY=$(openssl rand -hex 16)

cat > "${ENV_FILE_PATH}" << EOF
# --- System & Tenant Config (Generated by v2.3.0) ---
COMPOSE_PROJECT_NAME=${TENANT_ID}
TENANT_UID=${TENANT_UID}
TENANT_GID=${TENANT_GID}
DOMAIN=${DOMAIN}
DATA_ROOT=${TENANT_DIR}
TENANT_DIR=${TENANT_DIR}

# --- Caddy & SSL (CRITICAL: FILL THESE OUT) ---
ACME_EMAIL=hosting@datasquiz.net
CF_API_TOKEN=your-cloudflare-api-token

# --- Service Enablement (Defaults) ---
ENABLE_POSTGRES=true
ENABLE_REDIS=true
ENABLE_QDRANT=true
ENABLE_OLLAMA=true
ENABLE_OPENWEBUI=true
ENABLE_N8N=true
ENABLE_FLOWISE=true
ENABLE_ANYTHINGLLM=true
ENABLE_LITELLM=true
ENABLE_AUTHENTIK=true
ENABLE_PROMETHEUS=true
ENABLE_GRAFANA=true
ENABLE_CADDY=true

# --- Service Configuration ---
POSTGRES_SERVICE_NAME=postgres
REDIS_SERVICE_NAME=redis
QDRANT_SERVICE_NAME=qdrant
OLLAMA_SERVICE_NAME=ollama
N8N_SERVICE_NAME=n8n
FLOWISE_SERVICE_NAME=flowise
OPENWEBUI_SERVICE_NAME=openwebui
ANYTHINGLLM_SERVICE_NAME=anythingllm
LITELLM_SERVICE_NAME=litellm
GRAFANA_SERVICE_NAME=grafana
PROMETHEUS_SERVICE_NAME=prometheus
AUTHENTIK_SERVICE_NAME=authentik-server

# --- Port Configuration ---
POSTGRES_PORT=5432
REDIS_PORT=6379
QDRANT_PORT=6333
OLLAMA_PORT=11434
N8N_PORT=5678
FLOWISE_PORT=3000
OPENWEBUI_PORT=8080
ANYTHINGLLM_PORT=3001
LITELLM_PORT=4000
GRAFANA_PORT=3000
PROMETHEUS_PORT=9090
AUTHENTIK_PORT=9000
CADDY_HTTP_PORT=80
CADDY_HTTPS_PORT=443

# --- Secrets & Keys (Auto-generated) ---
POSTGRES_USER=${TENANT_ID}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${TENANT_ID}
REDIS_PASSWORD=${REDIS_PASSWORD}
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
QDRANT_API_KEY=${QDRANT_API_KEY}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
N8N_USER=admin
N8N_PASSWORD=admin123

# --- Database Configuration ---
DATABASE_TYPE=postgres
VECTOR_DB=qdrant
LLM_PROVIDERS=local

# --- SSL & Security ---
SSL_TYPE=acme
PROJECT_PREFIX=ai-
EOF
ok "Generated complete and compliant .env file."

ok "Phase 1 Setup COMPLETE. The environment is now 100% ready for deployment via script-2."
