#!/usr/bin/env bash
# =============================================================================
# Script 1: System Compiler - README COMPLIANT (NON-INTERACTIVE TEST)
# =============================================================================

set -euo pipefail

# Auto-configure for testing
TENANT_ID="datasquiz"
PREFIX="ai"
BASE_DOMAIN="ai.datasquiz.net"
PUID=$(id -u)
PGID=$(id -g)
PLATFORM_ARCH=$(uname -m)
GPU_TYPE="cpu"

# Services
POSTGRES_ENABLED=true
REDIS_ENABLED=true
OLLAMA_ENABLED=true
LITELLM_ENABLED=true
OPEN_WEBUI_ENABLED=true
QDRANT_ENABLED=true
CADDY_ENABLED=false

# Ports
POSTGRES_PORT=5432
REDIS_PORT=6379
OLLAMA_PORT=11434
LITELLM_PORT=4000
OPEN_WEBUI_PORT=3000
QDRANT_PORT=6333

# Database
POSTGRES_USER=aiplatform
POSTGRES_PASSWORD=aiplatform123
POSTGRES_DB=aiplatform

# Paths
BASE_DIR="/mnt/${TENANT_ID}"
CONFIG_DIR="${BASE_DIR}/config"
DATA_DIR="${BASE_DIR}/data"
LOGS_DIR="${BASE_DIR}/logs"
DOCKER_NETWORK="${PREFIX}-${TENANT_ID}-network"
DOCKER_SUBNET="172.20.0.0/16"

echo "=== Script 1: System Compiler (Non-Interactive Test) ==="
echo "Tenant: ${TENANT_ID}"

# Create directories
echo "Creating directory structure..."
mkdir -p "$BASE_DIR" "$CONFIG_DIR" "$DATA_DIR" "$LOGS_DIR"
mkdir -p "$DATA_DIR/postgres" "$DATA_DIR/redis" "$DATA_DIR/ollama" "$DATA_DIR/qdrant"
chown -R "$PUID:$PGID" "$BASE_DIR"

# Write platform.conf
echo "Creating platform.conf..."
cat > "${CONFIG_DIR}/platform.conf" << EOF
# =============================================================================
# AI Platform Configuration - PRIMARY SOURCE OF TRUTH (README P1)
# Generated by Script 1 on $(date)
# Tenant: ${TENANT_ID}
# =============================================================================

# ── TENANT CONFIGURATION ─────────────────────────────────────────────────────
TENANT_ID=${TENANT_ID}
PREFIX=${PREFIX}
BASE_DOMAIN=${BASE_DOMAIN}

# ── USER CONFIGURATION (README P7) ───────────────────────────────────────────────
PUID=${PUID}
PGID=${PGID}

# ── PLATFORM SETTINGS ───────────────────────────────────────────────────────
PLATFORM_ARCH=${PLATFORM_ARCH}
GPU_TYPE=${GPU_TYPE}

# ── PATHS (DERIVED) ───────────────────────────────────────────────────────
BASE_DIR=${BASE_DIR}
CONFIG_DIR=${CONFIG_DIR}
DATA_DIR=${DATA_DIR}
LOGS_DIR=${LOGS_DIR}
DOCKER_NETWORK=${DOCKER_NETWORK}
DOCKER_SUBNET=${DOCKER_SUBNET}

# ── SERVICE ENABLEMENT ───────────────────────────────────────────────────────
POSTGRES_ENABLED=${POSTGRES_ENABLED}
REDIS_ENABLED=${REDIS_ENABLED}
OLLAMA_ENABLED=${OLLAMA_ENABLED}
LITELLM_ENABLED=${LITELLM_ENABLED}
OPEN_WEBUI_ENABLED=${OPEN_WEBUI_ENABLED}
QDRANT_ENABLED=${QDRANT_ENABLED}
CADDY_ENABLED=${CADDY_ENABLED}

# ── PORT CONFIGURATION ───────────────────────────────────────────────────────
POSTGRES_PORT=${POSTGRES_PORT}
REDIS_PORT=${REDIS_PORT}
OLLAMA_PORT=${OLLAMA_PORT}
LITELLM_PORT=${LITELLM_PORT}
OPEN_WEBUI_PORT=${OPEN_WEBUI_PORT}
QDRANT_PORT=${QDRANT_PORT}

# ── DATABASE CONFIGURATION ───────────────────────────────────────────────────
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
EOF

chmod 600 "${CONFIG_DIR}/platform.conf"
chown "$PUID:$PGID" "${CONFIG_DIR}/platform.conf"

echo "✓ platform.conf created"
echo "✓ Directory structure created"
echo "✓ Script 1 complete"

echo ""
echo "Next steps:"
echo "  1. Deploy services: bash scripts/2-deploy-services.sh ${TENANT_ID}"
echo "  2. Verify deployment: bash scripts/3-configure-services.sh ${TENANT_ID}"
