#!/bin/bash
# Script 2: Deploy Services - Fixed Version with Final Output
# Fixed version with analysis.md improvements and proper final health check

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[$(date +'%H:%M:%S')]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date +'%H:%M:%S')] WARNING:${NC} $1"; }
error(){ echo -e "${RED}[$(date +'%H:%M:%S')] ERROR:${NC} $1"; }
info() { echo -e "${BLUE}[$(date +'%H:%M:%S')] INFO:${NC} $1"; }

# Configuration paths - loaded from .env
ENV_FILE="${ENV_FILE:-$(sudo ls -t /mnt/data/*/.env 2>/dev/null | head -1)}"
TENANT_DIR="$(dirname "${ENV_FILE}")"
PLATFORM_DIR="${TENANT_DIR}"
COMPOSE_FILE="${PLATFORM_DIR}/docker-compose.yml"

# ─── Load environment ────────────────────────────────────────────────
[[ -z "${ENV_FILE:-}" || ! -f "${ENV_FILE}" ]] && {
    error "Cannot find .env file. Run script 1 first."
    exit 1
}

# Robustly load variables from .env file
while IFS= read -r line || [[ -n "$line" ]]; do
    # Ignore comments and empty lines
    if [[ "$line" =~ ^\s*# || -z "$line" ]]; then
        continue
    fi
    # Safely export variable - handle quotes and special characters
    if [[ "$line" =~ ^export[[:space:]]*([^=]+)=(.*)$ ]]; then
        # Handle 'export KEY=VALUE' format
        export "${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
    elif [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
        # Handle 'KEY=VALUE' format
        export "${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
    fi
done < "${ENV_FILE}"

# Export critical variables for Docker Compose context
export PLATFORM_DIR DATA_ROOT COMPOSE_PROJECT_NAME TENANT_UID TENANT_GID SERVER_IP

log "Environment variables loaded successfully."

# ─── Structured Logging Setup ───────────────────────────────────────
# Ensure logs directory exists in tenant data directory as per README.md principle
mkdir -p "${DATA_ROOT}/logs"
LOG_FILE="${DATA_ROOT}/logs/script-2-$(date +%Y%m%d-%H%M%S).log"

# Redirect all subsequent output to log file and screen
exec > >(tee -a "${LOG_FILE}") 2>&1

log "======= AI Platform Deployment Starting ======="
log "All subsequent output will be logged to: ${LOG_FILE}"
log "Using .env: ${ENV_FILE}"

# Get tenant UID/GID
TENANT_UID=$(id -u "${TENANT_USER:-${SUDO_USER:-$(logname)}}")
TENANT_GID=$(id -g "${TENANT_USER:-${SUDO_USER:-$(logname)}}")

# ─── Root check ───────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root (sudo bash scripts/2-deploy-services.sh)"
    exit 1
fi

# ─── Docker Environment Setup ───────────────────────────────────────
# Set Docker environment variables to ensure proper socket access
export DOCKER_HOST=unix:///var/run/docker.sock
export DOCKER_CONTEXT=default

# ─── Docker daemon ────────────────────────────────────────────────────
log "Ensuring Docker daemon is running..."
if ! systemctl is-active --quiet docker; then
    log "Starting Docker daemon..."
    systemctl start docker
    sleep 5
fi

# Verify Docker socket accessibility
if ! docker info &>/dev/null; then
    error "Docker daemon is not responding. Check: systemctl status docker"
    exit 1
fi
log "Docker daemon OK"

# ─── Create required directories ─────────────────────────────────────
log "Creating required bind-mount directories..."
mkdir -p "${PLATFORM_DIR}/caddy/data"
mkdir -p "${PLATFORM_DIR}/postgres"
mkdir -p "${PLATFORM_DIR}/redis"
mkdir -p "${PLATFORM_DIR}/ollama"
mkdir -p "${PLATFORM_DIR}/qdrant"
mkdir -p "${PLATFORM_DIR}/prometheus"
mkdir -p "${PLATFORM_DIR}/grafana"
mkdir -p "${PLATFORM_DIR}/prometheus/data"
mkdir -p "${PLATFORM_DIR}/n8n"
mkdir -p "${PLATFORM_DIR}/flowise"
mkdir -p "${PLATFORM_DIR}/openwebui"
mkdir -p "${PLATFORM_DIR}/anythingllm"
mkdir -p "${PLATFORM_DIR}/litellm"
mkdir -p "${PLATFORM_DIR}/authentik/media"
mkdir -p "${PLATFORM_DIR}/authentik/custom-templates"

# Create prometheus config
cat > "${PLATFORM_DIR}/prometheus/prometheus.yml" << EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['${COMPOSE_PROJECT_NAME}-prometheus:9090']
EOF

chown -R "${TENANT_UID}:${TENANT_GID}" "${PLATFORM_DIR}"
chmod -R 755 "${PLATFORM_DIR}"
log "Directories ready"

# ─── Generate clean docker-compose.yml ───────────────────────────
log "Generating docker-compose.yml → ${COMPOSE_FILE}"

cat > "${COMPOSE_FILE}" << EOF
# Auto-generated by deployment script
services:
  postgres:
    image: postgres:15-alpine
    container_name: \${COMPOSE_PROJECT_NAME}-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=\${POSTGRES_USER}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
      - POSTGRES_DB=\${POSTGRES_DB}
    volumes:
      - \${PLATFORM_DIR}/postgres:/var/lib/postgresql/data
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: \${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    command: redis-server --requirepass \${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - \${PLATFORM_DIR}/redis:/data
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: \${COMPOSE_PROJECT_NAME}-ollama
    restart: unless-stopped
    user: "\${TENANT_UID}:\${TENANT_GID}"
    ports:
      - "\${OLLAMA_PORT:-11434}:11434"
    environment:
      - OLLAMA_PORT=\${OLLAMA_INTERNAL_PORT}
    volumes:
      - \${PLATFORM_DIR}/ollama:/root/.ollama
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:\${OLLAMA_INTERNAL_PORT}/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: \${COMPOSE_PROJECT_NAME}-qdrant
    restart: unless-stopped
    ports:
      - "\${QDRANT_INTERNAL_HTTP_PORT:-6333}:6333"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=\${QDRANT_INTERNAL_HTTP_PORT}
    volumes:
      - \${PLATFORM_DIR}/qdrant:/qdrant/storage
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:\${QDRANT_INTERNAL_HTTP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prometheus:
    image: prom/prometheus:latest
    container_name: \${COMPOSE_PROJECT_NAME}-prometheus
    restart: unless-stopped
    user: "\${TENANT_UID}:\${TENANT_GID}"
    ports:
      - "9090:9090"
    volumes:
      - \${PLATFORM_DIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - \${PLATFORM_DIR}/prometheus/data:/prometheus
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  grafana:
    image: grafana/grafana:latest
    container_name: \${COMPOSE_PROJECT_NAME}-grafana
    restart: unless-stopped
    user: "\${TENANT_UID}:\${TENANT_GID}"
    ports:
      - "\${GRAFANA_PORT:-3002}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=\${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - \${PLATFORM_DIR}/grafana:/var/lib/grafana
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  caddy:
    image: caddy:2-alpine
    container_name: \${COMPOSE_PROJECT_NAME}-caddy
    restart: unless-stopped
    user: "\${TENANT_UID}:\${TENANT_GID}"
    ports:
      - "\${CADDY_HTTP_PORT:-80}:80"
      - "\${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - \${PLATFORM_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - \${PLATFORM_DIR}/caddy/data:/data
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - postgres
      - redis
      - ollama
      - qdrant
      - prometheus
      - grafana
      - \${COMPOSE_PROJECT_NAME}-openwebui
      - \${COMPOSE_PROJECT_NAME}-n8n
      - \${COMPOSE_PROJECT_NAME}-flowise
      - \${COMPOSE_PROJECT_NAME}-anythingllm
      - \${COMPOSE_PROJECT_NAME}-litellm
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ── n8n ──────────────────────────────────────────────────────────────
$([ "\${ENABLE_N8N:-true}" = "true" ] && cat << BLOCK

  n8n:
    image: n8nio/n8n:latest
    container_name: \${COMPOSE_PROJECT_NAME}-n8n
    restart: unless-stopped
    ports:
      - "\${N8N_PORT:-5678}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=\${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=\${N8N_PASSWORD}
      - N8N_HOST=n8n.\${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.\${DOMAIN}
      - GENERIC_TIMEZONE=\${TIMEZONE:-UTC}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=\${COMPOSE_PROJECT_NAME}-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=\${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=\${POSTGRES_PASSWORD}
    volumes:
      - \${PLATFORM_DIR}/n8n:/home/node/.n8n
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
BLOCK
)

# ── Flowise ──────────────────────────────────────────────────────────
$([ "\${ENABLE_FLOWISE:-true}" = "true" ] && cat << BLOCK

  flowise:
    image: flowiseai/flowise:latest
    container_name: \${COMPOSE_PROJECT_NAME}-flowise
    restart: unless-stopped
    ports:
      - "\${FLOWISE_PORT:-3000}:3000"
    environment:
      - FLOWISE_USERNAME=\${FLOWISE_USER:-admin}
      - FLOWISE_PASSWORD=\${FLOWISE_PASSWORD}
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
    volumes:
      - \${PLATFORM_DIR}/flowise:/root/.flowise
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
BLOCK
)

# ── Open WebUI ───────────────────────────────────────────────────────
$([ "\${ENABLE_OPENWEBUI:-true}" = "true" ] && cat << BLOCK

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: \${COMPOSE_PROJECT_NAME}-openwebui
    restart: unless-stopped
    ports:
      - "\${OPENWEBUI_PORT:-8080}:8080"
    environment:
      - OLLAMA_BASE_URL=http://\${COMPOSE_PROJECT_NAME}-ollama:11434
      - WEBUI_SECRET_KEY=\${OPENWEBUI_SECRET_KEY:-\$(openssl rand -hex 32)}
    volumes:
      - \${PLATFORM_DIR}/openwebui:/app/backend/data
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
BLOCK
)

# ── AnythingLLM ──────────────────────────────────────────────────────
$([ "\${ENABLE_ANYTHINGLLM:-true}" = "true" ] && cat << BLOCK

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: \${COMPOSE_PROJECT_NAME}-anythingllm
    restart: unless-stopped
    ports:
      - "\${ANYTHINGLLM_PORT:-3001}:3001"
    environment:
      - JWT_SECRET=\${ANYTHINGLLM_JWT_SECRET}
      - OLLAMA_BASE_PATH=http://\${COMPOSE_PROJECT_NAME}-ollama:11434
      - QDRANT_ENDPOINT=http://\${COMPOSE_PROJECT_NAME}-qdrant:6333
      - QDRANT_API_KEY=\${QDRANT_API_KEY}
      - STORAGE_DIR=/app/server/storage
      - DATABASE_URL=sqlite:///app/server/storage/anythingllm.db
      - DATABASE_PATH=/app/server/storage/anythingllm.db
    volumes:
      - \${PLATFORM_DIR}/anythingllm:/app/server/storage
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - ollama
      - qdrant
    healthcheck:
      test: ["CMD", "test", "-f", "/app/server/storage/anythingllm.db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
BLOCK
)

# ── LiteLLM ──────────────────────────────────────────────────────────
$([ "\${ENABLE_LITELLM:-true}" = "true" ] && cat << BLOCK

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: \${COMPOSE_PROJECT_NAME}-litellm
    restart: unless-stopped
    ports:
      - "\${LITELLM_PORT:-4000}:4000"
    environment:
      - LITELLM_MASTER_KEY=\${LITELLM_MASTER_KEY}
      - DATABASE_URL=sqlite://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${COMPOSE_PROJECT_NAME}-postgres:5432/litellm
      - STORE_MODEL_IN_DB=True
    volumes:
      - \${PLATFORM_DIR}/litellm:/app/config
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
BLOCK
)

# ── Authentik ────────────────────────────────────────────────────────
$([ "${ENABLE_AUTHENTIK:-false}" = "true" ] && cat << BLOCK

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: \${COMPOSE_PROJECT_NAME}-authentik
    restart: unless-stopped
    command: server
    ports:
      - "\${AUTHENTIK_PORT:-9000}:9000"
    environment:
      - AUTHENTIK_REDIS__HOST=\${COMPOSE_PROJECT_NAME}-redis
      - AUTHENTIK_POSTGRESQL__HOST=\${COMPOSE_PROJECT_NAME}-postgres
      - AUTHENTIK_POSTGRESQL__USER=\${POSTGRES_USER}
      - AUTHENTIK_POSTGRESQL__PASSWORD=\${POSTGRES_PASSWORD}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_SECRET_KEY=\${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_BOOTSTRAP_PASSWORD=\${AUTHENTIK_BOOTSTRAP_PASSWORD}
      - AUTHENTIK_BOOTSTRAP_EMAIL=\${ADMIN_EMAIL}
    volumes:
      - \${PLATFORM_DIR}/authentik/media:/media
      - \${PLATFORM_DIR}/authentik/custom-templates:/templates
    networks:
      - \${COMPOSE_PROJECT_NAME}-net
    depends_on:
      - postgres
      - redis
BLOCK
)

networks:
  ai-datasquiz-net:
    driver: bridge
EOF

# Ensure proper ownership
chown "${TENANT_UID}:${TENANT_GID}" "${COMPOSE_FILE}"
log "Docker Compose generated successfully"

# ─── Validate compose config ──────────────────────────────────────────
log "Validating Docker Compose configuration..."
cd "${PLATFORM_DIR}"
if ! docker compose config --quiet 2>&1; then
    error "docker-compose.yml is invalid. Output:"
    docker compose config 2>&1
    exit 1
fi
log "Configuration valid"

# ─── Deploy stack ──────────────────────────────────────────────────
log "Starting deployment..."
docker compose down --remove-orphans 2>/dev/null || true
docker compose up -d

# ─── Wait for containers to initialise ─────────────────────────────
log "Waiting 30 seconds for containers to initialise..."
sleep 30

# ─── Verify deployment with detailed health check ───────────────────────
log "Verifying deployment status..."

echo ""
echo "=========================================="
echo "  AI Platform — Deployment Health Check"
echo "=========================================="

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')

# Enhanced Service Health Check with URL verification
echo ""
echo "=========================================="
echo "  🏥 AI Platform — Enhanced Health Check"
echo "=========================================="

# Check each service
SERVICES=(
    "postgres" "redis" "ollama" "qdrant"
    "prometheus" "grafana" "caddy"
    "n8n" "flowise" "openwebui" "anythingllm" "litellm"
)
FAILED_SERVICES=()
RUNNING_SERVICES=()

for service in "${SERVICES[@]}"; do
    if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-${service}.*Up"; then
        RUNNING_SERVICES+=("$service")
        log "✅ ${service}: RUNNING"
    else
        FAILED_SERVICES+=("$service")
        log "❌ ${service}: FAILED"
    fi
done

# Service-specific health checks
echo ""
echo "🔍 SERVICE-SPECIFIC HEALTH CHECKS:"

# Check database services
echo "  📊 DATABASE SERVICES:"
if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-postgres.*Up"; then
    echo "    ✅ PostgreSQL: Container running"
    if docker exec ai-datasquiz-postgres pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" &>/dev/null; then
        echo "    ✅ PostgreSQL: Database responding"
    else
        echo "    ❌ PostgreSQL: Database not responding"
    fi
else
    echo "    ❌ PostgreSQL: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-redis.*Up"; then
    echo "    ✅ Redis: Container running"
    if docker exec ai-datasquiz-redis redis-cli ping &>/dev/null; then
        echo "    ✅ Redis: Service responding"
    else
        echo "    ❌ Redis: Service not responding"
    fi
else
    echo "    ❌ Redis: Container not running"
fi

# Check AI services
echo "  🤖 AI SERVICES:"
if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-ollama.*Up"; then
    echo "    ✅ Ollama: Container running"
    if curl -s http://localhost:11434/api/tags &>/dev/null; then
        echo "    ✅ Ollama: API responding"
    else
        echo "    ❌ Ollama: API not responding"
    fi
else
    echo "    ❌ Ollama: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-qdrant.*Up"; then
    echo "    ✅ Qdrant: Container running"
    if curl -s http://localhost:6333/health &>/dev/null; then
        echo "    ✅ Qdrant: Health endpoint responding"
    else
        echo "    ❌ Qdrant: Health endpoint not responding"
    fi
else
    echo "    ❌ Qdrant: Container not running"
fi

# Check web services
echo "  🌐 WEB SERVICES:"
if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-n8n.*Up"; then
    echo "    ✅ n8n: Container running"
    if curl -s http://localhost:5678 &>/dev/null; then
        echo "    ✅ n8n: Web interface responding"
    else
        echo "    ❌ n8n: Web interface not responding"
    fi
else
    echo "    ❌ n8n: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-flowise.*Up"; then
    echo "    ✅ Flowise: Container running"
    if curl -s http://localhost:3000 &>/dev/null; then
        echo "    ✅ Flowise: Web interface responding"
    else
        echo "    ❌ Flowise: Web interface not responding"
    fi
else
    echo "    ❌ Flowise: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-openwebui.*Up"; then
    echo "    ✅ OpenWebUI: Container running"
    if curl -s http://localhost:8080 &>/dev/null; then
        echo "    ✅ OpenWebUI: Web interface responding"
    else
        echo "    ❌ OpenWebUI: Web interface not responding"
    fi
else
    echo "    ❌ OpenWebUI: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-anythingllm.*Up"; then
    echo "    ✅ AnythingLLM: Container running"
    if curl -s http://localhost:3001/api/ping &>/dev/null; then
        echo "    ✅ AnythingLLM: API responding"
    else
        echo "    ❌ AnythingLLM: API not responding"
    fi
else
    echo "    ❌ AnythingLLM: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-litellm.*Up"; then
    echo "    ✅ LiteLLM: Container running"
    if curl -s http://localhost:4000/health &>/dev/null; then
        echo "    ✅ LiteLLM: Health endpoint responding"
    else
        echo "    ❌ LiteLLM: Health endpoint not responding"
    fi
else
    echo "    ❌ LiteLLM: Container not running"
fi

# Check monitoring services
echo "  📊 MONITORING SERVICES:"
if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-prometheus.*Up"; then
    echo "    ✅ Prometheus: Container running"
    if curl -s http://localhost:9090/metrics &>/dev/null; then
        echo "    ✅ Prometheus: Metrics endpoint responding"
    else
        echo "    ❌ Prometheus: Metrics endpoint not responding"
    fi
else
    echo "    ❌ Prometheus: Container not running"
fi

if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-grafana.*Up"; then
    echo "    ✅ Grafana: Container running"
    if curl -s http://localhost:3002/api/health &>/dev/null; then
        echo "    ✅ Grafana: Health endpoint responding"
    else
        echo "    ❌ Grafana: Health endpoint not responding"
    fi
else
    echo "    ❌ Grafana: Container not running"
fi

# Check reverse proxy
echo "  🌐 REVERSE PROXY:"
if docker ps --format "table {{.Names}}\t{{.Status}}" | grep -q "ai-datasquiz-caddy.*Up"; then
    echo "    ✅ Caddy: Container running"
    if curl -s http://localhost:80 &>/dev/null; then
        echo "    ✅ Caddy: HTTP endpoint responding"
    else
        echo "    ❌ Caddy: HTTP endpoint not responding"
    fi
    if curl -s https://localhost:443 &>/dev/null; then
        echo "    ✅ Caddy: HTTPS endpoint responding"
    else
        echo "    ❌ Caddy: HTTPS endpoint not responding"
    fi
else
    echo "    ❌ Caddy: Container not running"
fi

echo ""
echo "=========================================="

# Summary with Service-Specific Logging
echo ""
echo "=========================================="
if [ ${#FAILED_SERVICES[@]} -eq 0 ]; then
    echo "  🎉 ALL SERVICES RUNNING SUCCESSFULLY!"
    echo "  🌐 Access URLs listed above"
    echo "  📊 Grafana: http://${SERVER_IP}:3002 (admin/${GRAFANA_PASSWORD})"
else
    echo "  ⚠️  ${#FAILED_SERVICES[@]} services failed:"
    for failed in "${FAILED_SERVICES[@]}"; do
        echo "     - $failed"
        echo "  🔍 Capturing Docker logs for $failed..."
        echo "=========================================="
        docker logs "ai-datasquiz-${failed}" --tail 50 2>&1 | tee -a "${LOG_FILE}"
        echo "=========================================="
    done
fi
echo "=========================================="
echo ""

# Final concise deployment status
log "======= DEPLOYMENT SUMMARY ======="
# Calculate success rate
SUCCESS_RATE=$((${#RUNNING_SERVICES[@]} * 100 / ${#SERVICES[@]}))

log "Success Rate: ${SUCCESS_RATE}% (${#RUNNING_SERVICES[@]}/${#SERVICES[@]} services)"
log "Failed Services: ${#FAILED_SERVICES[@]}"
log "Full logs: ${LOG_FILE}"
log "=========================================="
echo ""

if [ ${#FAILED_SERVICES[@]} -gt 0 ]; then
    warn "Some services failed to start. Check logs for details."
    exit 1
else
    log "Deployment complete! All services are healthy."
fi
