#!/usr/bin/env bash
# =============================================================================
# Script 2: Deploy Services - PURE DEPLOYMENT ENGINE
# =============================================================================
# PURPOSE: Reads pre-configured environment and deploys services.
#          Assumes all setup and permissions are already correct.
# USAGE:   sudo bash scripts/2-deploy-services.sh <tenant_id>
# =============================================================================

set -euo pipefail

# --- Tenant ID Check ---
if [[ -z "${1:-}" ]]; then
    echo "ERROR: TENANT_ID is required. Usage: sudo bash $0 <tenant_id>" >&2
    exit 1
fi
TENANT_ID="$1"

# --- Colors and Logging ---
RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' CYAN='\033[0;36m' NC='\033[0m'
log() { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail() { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# --- Environment Setup ---
TENANT_DIR="/mnt/data/${TENANT_ID}"
ENV_FILE="${TENANT_DIR}/.env"
COMPOSE_FILE="${TENANT_DIR}/docker-compose.yml"

if [[ ! -f "${ENV_FILE}" ]]; then
    fail "Environment file not found for tenant '${TENANT_ID}' at ${ENV_FILE}"
fi

log "Loading environment from: ${ENV_FILE}"
set -a; source "${ENV_FILE}"; set +a

# --- Logging to File ---
LOG_DIR="${TENANT_DIR}/logs"
mkdir -p "${LOG_DIR}"
LOG_FILE="${LOG_DIR}/deploy-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "${LOG_FILE}") 2>&1
log "All output is now logged to: ${LOG_FILE}"

# --- Docker Check ---
if ! docker info &>/dev/null; then
    fail "Docker is not running. Please start Docker and try again."
fi
ok "Docker is active."

# =============================================================================
# DOCKER COMPOSE GENERATION
# =============================================================================
log "Generating docker-compose.yml for tenant '${TENANT_ID}'..."

# Start with clean compose file
cat > "${COMPOSE_FILE}" << EOF
# Auto-generated by deployment script for tenant: ${TENANT_ID}
# Generated on: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
services:

EOF

# --- Service Generators ---
add_postgres() {
    cat >> "${COMPOSE_FILE}" << EOF

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: \${POSTGRES_DB:-postgres}
    volumes:
      - \${TENANT_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

EOF
    ok "Added 'postgres' service."
}

add_redis() {
    cat >> "${COMPOSE_FILE}" << EOF

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - default
    command: redis-server --requirepass \${REDIS_PASSWORD}
    volumes:
      - \${TENANT_DIR}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

EOF
    ok "Added 'redis' service."
}

add_ollama() {
    cat >> "${COMPOSE_FILE}" << EOF

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - \${TENANT_DIR}/ollama:/root/.ollama

EOF
    ok "Added 'ollama' service."
}

add_openwebui() {
    cat >> "${COMPOSE_FILE}" << EOF

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    networks:
      - default
    ports:
      - "\${OPENWEBUI_PORT:-8080}:8080"
    environment:
      OLLAMA_BASE_URL: http://\${OLLAMA_SERVICE_NAME:-ollama}:\${OLLAMA_PORT:-11434}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    volumes:
      - \${TENANT_DIR}/openwebui:/app/backend/data
    depends_on:
      - ollama

EOF
    ok "Added 'openwebui' service."
}

add_n8n() {
    cat >> "${COMPOSE_FILE}" << EOF

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "\${N8N_PORT:-5678}:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: \${POSTGRES_SERVICE_NAME:-postgres}
      DB_POSTGRESDB_DATABASE: \${POSTGRES_DB:-postgres}
      DB_POSTGRESDB_USER: \${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: \${POSTGRES_PASSWORD}
      N8N_BASIC_AUTH_USER: \${N8N_USER}
      N8N_BASIC_AUTH_PASSWORD: \${N8N_PASSWORD}
    volumes:
      - \${TENANT_DIR}/n8n:/home/node/.n8n
    depends_on:
      - postgres

EOF
    ok "Added 'n8n' service."
}

add_flowise() {
    cat >> "${COMPOSE_FILE}" << EOF

  flowise:
    image: flowiseai/flowise:latest
    restart: unless-stopped
    ports:
      - "\${FLOWISE_PORT:-3000}:3000"
    networks:
      - default

EOF
    ok "Added 'flowise' service."
}

add_anythingllm() {
    cat >> "${COMPOSE_FILE}" << EOF

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "\${ANYTHINGLLM_PORT:-3001}:8888"
    environment:
      VECTOR_DB: qdrant
      QDRANT_ENDPOINT: http://\${QDRANT_SERVICE_NAME:-qdrant}:\${QDRANT_PORT:-6333}
      QDRANT_API_KEY: \${QDRANT_API_KEY}
      OLLAMA_BASE_URL: http://\${OLLAMA_SERVICE_NAME:-ollama}:\${OLLAMA_PORT:-11434}
      STORAGE_DIR: /app/server/storage
      DATABASE_PATH: /app/server/storage/anythingllm.db
      PORT: 8888
    volumes:
      - \${TENANT_DIR}/anythingllm:/app/server/storage
      - \${TENANT_DIR}/anythingllm/tmp:/tmp
    depends_on:
      - ollama
      - qdrant

EOF
    ok "Added 'anythingllm' service."
}

add_litellm() {
    cat >> "${COMPOSE_FILE}" << EOF

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "\${LITELLM_PORT:-4000}:4000"
    environment:
      LITELLM_PORT: 4000
    volumes:
      - \${TENANT_DIR}/litellm:/app/data
    depends_on:
      - ollama

EOF
    ok "Added 'litellm' service."
}

add_grafana() {
    cat >> "${COMPOSE_FILE}" << EOF

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - "\${GRAFANA_PORT:-3002}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: \${GRAFANA_PASSWORD}
    volumes:
      - \${TENANT_DIR}/grafana:/var/lib/grafana
      - \${TENANT_DIR}/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

EOF
    ok "Added 'grafana' service."
}

add_prometheus() {
    cat >> "${COMPOSE_FILE}" << EOF

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "65534:65534"
    networks:
      - default
    volumes:
      - \${TENANT_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml
      - \${TENANT_DIR}/prometheus-data:/prometheus

EOF
    ok "Added 'prometheus' service."
}

add_qdrant() {
    cat >> "${COMPOSE_FILE}" << EOF

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    networks:
      - default
    volumes:
      - \${TENANT_DIR}/qdrant:/qdrant/storage

EOF
    ok "Added 'qdrant' service."
}

add_authentik() {
    cat >> "${COMPOSE_FILE}" << EOF

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    networks:
      - default
    user: "\${TENANT_UID}:\${TENANT_GID}"
    environment:
      AUTHENTIK_SECRET_KEY: \${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_POSTGRESQL__HOST: \${POSTGRES_SERVICE_NAME:-postgres}
      AUTHENTIK_POSTGRESQL__NAME: \${POSTGRES_DB:-authentik}
      AUTHENTIK_POSTGRESQL__USER: \${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - \${TENANT_DIR}/authentik/media:/media
      - \${TENANT_DIR}/authentik/custom-templates:/templates
    depends_on:
      - postgres

EOF
    ok "Added 'authentik-server' service."
}

add_caddy() {
    if [[ "${ENABLE_CADDY}" == "true" ]]; then
        cat >> "${COMPOSE_FILE}" << EOF

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    networks:
      - default
    user: "\${TENANT_UID}:\${TENANT_GID}"
    ports:
      - "\${CADDY_HTTP_PORT:-80}:80"
      - "\${CADDY_HTTPS_PORT:-443}:443"
    environment:
      ACME_AGREE: "true"
    volumes:
      - \${TENANT_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - \${TENANT_DIR}/caddy/data:/data
      - \${TENANT_DIR}/caddy/config:/config
EOF

        # Add dynamic dependencies based on enabled services
        local deps_added=false
        if [[ "${ENABLE_N8N}" == "true" ]]; then
            echo "    depends_on:" >> "${COMPOSE_FILE}"
            echo "      - n8n" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_FLOWISE}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - flowise" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_OPENWEBUI}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - openwebui" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_ANYTHINGLLM}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - anythingllm" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_LITELLM}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - litellm" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_GRAFANA}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - grafana" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        if [[ "${ENABLE_AUTHENTIK}" == "true" ]]; then
            if [[ "$deps_added" == "false" ]]; then
                echo "    depends_on:" >> "${COMPOSE_FILE}"
            fi
            echo "      - authentik-server" >> "${COMPOSE_FILE}"
            deps_added=true
        fi
        
        ok "Added 'caddy' service with dynamic dependencies."
    fi
}
# --- Generate All Services ---
[[ "${ENABLE_POSTGRES}" == "true" ]] && add_postgres
[[ "${ENABLE_REDIS}" == "true" ]] && add_redis
[[ "${ENABLE_OLLAMA}" == "true" ]] && add_ollama
[[ "${ENABLE_OPENWEBUI}" == "true" ]] && add_openwebui
[[ "${ENABLE_N8N}" == "true" ]] && add_n8n
[[ "${ENABLE_FLOWISE}" == "true" ]] && add_flowise
[[ "${ENABLE_ANYTHINGLLM}" == "true" ]] && add_anythingllm
[[ "${ENABLE_LITELLM}" == "true" ]] && add_litellm
[[ "${ENABLE_GRAFANA}" == "true" ]] && add_grafana
[[ "${ENABLE_QDRANT}" == "true" ]] && add_qdrant
[[ "${ENABLE_PROMETHEUS}" == "true" ]] && add_prometheus
[[ "${ENABLE_AUTHENTIK}" == "true" ]] && add_authentik
[[ "${ENABLE_CADDY}" == "true" ]] && add_caddy

# --- Final Networks Block ---
cat >> "${COMPOSE_FILE}" << EOF

networks:
  default:
    name: \${COMPOSE_PROJECT_NAME}-net
EOF
ok "Compose file generation complete."

# =============================================================================
# DEPLOYMENT
# =============================================================================

cd "${TENANT_DIR}"

log "Validating final docker-compose.yml file..."
if ! docker compose config --quiet; then
    fail "Docker Compose configuration is invalid. Please check the logs."
fi
ok "Configuration is valid."

log "Deploying stack '${COMPOSE_PROJECT_NAME}'..."

# Stop any previous versions and remove orphans before starting
docker compose down --remove-orphans
docker compose up -d

ok "Deployment initiated successfully. Please allow a few minutes for all services to start."
log "Run 'docker compose ps' in '${TENANT_DIR}' to check status."

echo ""
ok "SCRIPT 2 COMPLETED SUCCESSFULLY."
echo ""

# =============================================================================
# URL TESTING FUNCTION
# =============================================================================
test_service_urls() {
    log "Testing service URLs to verify deployment..."
    
    # Colors for output
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
    
    # Test function
    test_url() {
        local url="$1"
        local description="$2"
        
        echo -n "Testing $description: "
        echo -n "$url "
        
        if curl -s -f -m 10 "$url" > /dev/null 2>&1; then
            echo -e "${GREEN}✅ SUCCESS${NC}"
            return 0
        else
            echo -e "${RED}❌ FAILED${NC}"
            return 1
        fi
    }
    
    echo ""
    echo "==============================================="
    echo "🔍 TESTING PROMISED URLS"
    echo "==============================================="
    echo ""
    
    # External HTTPS URL tests
    echo "🌐 EXTERNAL HTTPS URL TESTS"
    echo "================================"
    local external_success=0
    local external_total=0
    
    [[ "${ENABLE_N8N}" == "true" ]] && { test_url "https://n8n.${DOMAIN}" "n8n" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_FLOWISE}" == "true" ]] && { test_url "https://flowise.${DOMAIN}" "Flowise" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_OPENWEBUI}" == "true" ]] && { test_url "https://openwebui.${DOMAIN}" "Open WebUI" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_ANYTHINGLLM}" == "true" ]] && { test_url "https://anythingllm.${DOMAIN}" "AnythingLLM" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_LITELLM}" == "true" ]] && { test_url "https://litellm.${DOMAIN}" "LiteLLM" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_GRAFANA}" == "true" ]] && { test_url "https://grafana.${DOMAIN}" "Grafana" && ((external_success++)) || true; ((external_total++)); }
    [[ "${ENABLE_AUTHENTIK}" == "true" ]] && { test_url "https://auth.${DOMAIN}" "Authentik" && ((external_success++)) || true; ((external_total++)); }
    echo ""
    
    # Local access URL tests
    echo "🏠 LOCAL ACCESS URL TESTS"
    echo "================================"
    local local_success=0
    local local_total=0
    
    [[ "${ENABLE_OPENWEBUI}" == "true" ]] && { test_url "http://localhost:${OPENWEBUI_PORT:-8080}" "Open WebUI local" && ((local_success++)) || true; ((local_total++)); }
    [[ "${ENABLE_OLLAMA}" == "true" ]] && { test_url "http://localhost:${OLLAMA_PORT:-11434}/api/tags" "Ollama API local" && ((local_success++)) || true; ((local_total++)); }
    [[ "${ENABLE_QDRANT}" == "true" ]] && { test_url "http://localhost:${QDRANT_PORT:-6333}" "Qdrant local" && ((local_success++)) || true; ((local_total++)); }
    echo ""
    
    # Summary
    echo "==============================================="
    echo "📊 URL TESTING SUMMARY"
    echo "==============================================="
    echo "External URLs: $external_success/$external_total working"
    echo "Local URLs: $local_success/$local_total working"
    echo "==============================================="
    
    if [[ $external_success -eq $external_total && $local_success -eq $local_total ]]; then
        ok "All service URLs are accessible!"
        return 0
    else
        warn "Some service URLs are not accessible. Check service logs."
        return 1
    fi
}

# Wait for services to start and test URLs
log "Waiting 30 seconds for services to initialize..."
sleep 30

# Test service URLs
if test_service_urls; then
    ok "Deployment verification complete - all services accessible!"
else
    warn "Deployment completed but some services may need additional configuration."
fi
