#!/usr/bin/env bash
# =============================================================================
# Script 3: Mission Control — Function Library + CLI Dispatcher
# Sourced by: 0-cleanup.sh, 1-setup-system.sh, 2-deploy-services.sh
# Run directly for: service lifecycle, health, config, logs
# =============================================================================
set -euo pipefail

# ── Single Source of Truth for Paths ───────────────────────────────────────
# ALL paths resolve to /mnt/data/${TENANT} - NO EXCEPTIONS
MNT_ROOT="/mnt/data"
TENANT="${TENANT:-default}"
TENANT_DIR="${MNT_ROOT}/${TENANT}"
CONFIG_DIR="${TENANT_DIR}/configs"
DATA_DIR="${TENANT_DIR}/data"
LOGS_DIR="${TENANT_DIR}/logs"
COMPOSE_FILE="${TENANT_DIR}/docker-compose.yml"
ENV_FILE="${TENANT_DIR}/.env"  # Data confinement - everything under /mnt/data/tenant/

# ── Load Environment ────────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] && set -a && source "$ENV_FILE" && set +a

# ── Colors and Logging ────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

log_write() {
    local level="$1" msg="$2"
    local ts; ts="$(date '+%Y-%m-%d %H:%M:%S')"
    local logfile="${LOGS_DIR}/platform-$(date +%Y%m%d).log"
    mkdir -p "$LOGS_DIR"
    echo -e "[${ts}] [${level}] ${msg}" | tee -a "$logfile"
}

log_info()    { echo -e "${BLUE}ℹ${NC} $1";  log_write INFO    "$1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; log_write SUCCESS "$1"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $1"; log_write WARNING "$1"; }
log_error()   { echo -e "${RED}✗${NC} $1";  log_write ERROR   "$1"; }

# ── Directory Preparation with UID-Aware Ownership ─────────────────────────
prepare_directories() {
    log_info "Preparing tenant directories under ${TENANT_DIR}..."
    
    # Create ALL directories under /mnt/data/${TENANT}
    mkdir -p \
        "${DATA_DIR}/postgres" \
        "${DATA_DIR}/redis" \
        "${DATA_DIR}/qdrant/snapshots" \
        "${DATA_DIR}/ollama" \
        "${DATA_DIR}/openwebui" \
        "${DATA_DIR}/n8n" \
        "${DATA_DIR}/flowise" \
        "${DATA_DIR}/litellm" \
        "${DATA_DIR}/grafana/data" \
        "${DATA_DIR}/grafana/logs" \
        "${DATA_DIR}/prometheus" \
        "${DATA_DIR}/anythingllm" \
        "${DATA_DIR}/tailscale" \
        "${DATA_DIR}/openclaw" \
        "${DATA_DIR}/codeserver" \
        "${CONFIG_DIR}/litellm" \
        "${CONFIG_DIR}/postgres" \
        "${CONFIG_DIR}/caddy/data" \
        "${CONFIG_DIR}/caddy/config" \
        "${CONFIG_DIR}/prometheus" \
        "${LOGS_DIR}"

    # CRITICAL: Set ownership matching container UIDs exactly
    chown -R 70:"${TENANT_GID:-1001}"      "${DATA_DIR}/postgres"
    chown -R 999:"${TENANT_GID:-1001}"     "${DATA_DIR}/redis"
    chown -R 1000:"${TENANT_GID:-1001}"    "${DATA_DIR}/qdrant"
    chown -R 472:472                        "${DATA_DIR}/grafana"
    chown -R 65534:65534                    "${DATA_DIR}/prometheus"
    chown -R 1000:"${TENANT_GID:-1001}"    \
        "${DATA_DIR}/litellm" \
        "${DATA_DIR}/n8n" \
        "${DATA_DIR}/flowise" \
        "${DATA_DIR}/openwebui" \
        "${DATA_DIR}/ollama" \
        "${DATA_DIR}/anythingllm" \
        "${DATA_DIR}/tailscale" \
        "${DATA_DIR}/openclaw" \
        "${DATA_DIR}/codeserver"
    
    # Config directories owned by tenant for script access
    chown -R "${TENANT_UID:-1001}:${TENANT_GID:-1001}" "${CONFIG_DIR}"
    chown -R "${TENANT_UID:-1001}:${TENANT_GID:-1001}" "${LOGS_DIR}"
    
    log_success "Directories ready with correct UID ownership"
}

# ── Environment File Generation (Primitive Variables First) ───────────────────
generate_env() {
    log_info "Writing .env to ${ENV_FILE}..."
    mkdir -p "$(dirname "$ENV_FILE")"
    
    # PRIMITIVE VARIABLES FIRST - prevents unbound variable errors
    cat > "$ENV_FILE" <<EOF
# Generated by 1-setup-system.sh — do not edit manually
# ─── Core Identity ────────────────────────────────────────────────────────
TENANT=${TENANT_NAME}
DOMAIN=${BASE_DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
TENANT_UID=${REAL_UID}
TENANT_GID=${REAL_GID}

# ─── Paths (All resolve to /mnt/data/${TENANT}) ───────────────────────────
MNT_ROOT=${MNT_ROOT}
TENANT_DIR=/mnt/data/${TENANT_NAME}
CONFIG_DIR=/mnt/data/${TENANT_NAME}/configs
DATA_DIR=/mnt/data/${TENANT_NAME}/data
LOGS_DIR=/mnt/data/${TENANT_NAME}/logs
COMPOSE_FILE=/mnt/data/${TENANT_NAME}/docker-compose.yml

# ─── Database Credentials (Primitive) ───────────────────────────────────────
POSTGRES_DB=aiplatform
POSTGRES_USER=aiplatform
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_UID=70
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_UID=999
DB_PASSWORD=${DB_PASSWORD}

# ─── Derived Connection Strings (Use primitives above) ─────────────────────
DATABASE_URL=postgresql://aiplatform:\${POSTGRES_PASSWORD}@postgres:5432/aiplatform
LITELLM_DATABASE_URL=postgresql://aiplatform:\${POSTGRES_PASSWORD}@postgres:5432/litellm
OPENWEBUI_DATABASE_URL=postgresql://aiplatform:\${POSTGRES_PASSWORD}@postgres:5432/openwebui
REDIS_URL=redis://:\${REDIS_PASSWORD}@redis:6379

# ─── Service Secrets ────────────────────────────────────────────────────────
ADMIN_PASSWORD=${ADMIN_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
LITELLM_MASTER_KEY=\${JWT_SECRET}
LITELLM_SALT_KEY=\${ENCRYPTION_KEY}
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=\${ADMIN_PASSWORD}

# ─── API Keys (Empty if not set) ───────────────────────────────────────────
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}

# ─── Service Flags ────────────────────────────────────────────────────────
ENABLE_LITELLM=${ENABLE_LITELLM:-false}
ENABLE_OLLAMA=${ENABLE_OLLAMA:-false}
ENABLE_OPENWEBUI=${ENABLE_OPENWEBUI:-false}
ENABLE_N8N=${ENABLE_N8N:-false}
ENABLE_FLOWISE=${ENABLE_FLOWISE:-false}
ENABLE_ANYTHINGLLM=${ENABLE_ANYTHINGLLM:-false}
ENABLE_QDRANT=${ENABLE_QDRANT:-false}
ENABLE_MONITORING=${ENABLE_MONITORING:-false}
ENABLE_TAILSCALE=${ENABLE_TAILSCALE:-false}

# ─── Ports (All configurable) ───────────────────────────────────────────────
PORT_LITELLM=4000
PORT_OPENWEBUI=3000
PORT_N8N=5678
PORT_FLOWISE=3001
PORT_GRAFANA=3002
PORT_PROMETHEUS=9090
PORT_QDRANT=6333
PORT_ANYTHINGLLM=3003
PORT_OPENCLAW=18789

# ─── External Integrations ───────────────────────────────────────────────────
TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY:-}
GDRIVE_CLIENT_ID=${GDRIVE_CLIENT_ID:-}
GDRIVE_CLIENT_SECRET=${GDRIVE_CLIENT_SECRET:-}
GDRIVE_REFRESH_TOKEN=${GDRIVE_REFRESH_TOKEN:-}
OLLAMA_MODELS=${OLLAMA_MODELS:-llama3.1}

# ─── LiteLLM Routing Strategy ───────────────────────────────────────────────
LITELLM_ROUTING_STRATEGY=${LITELLM_ROUTING_STRATEGY:-least-busy}

# ─── Vector DB Selection ───────────────────────────────────────────────────
VECTOR_DB_TYPE=${VECTOR_DB_TYPE:-qdrant}

# ─── SSL Configuration ───────────────────────────────────────────────────────
USE_LETSENCRYPT=${USE_LETSENCRYPT:-false}
EOF
    chmod 600 "$ENV_FILE"
    log_success ".env written with correct variable ordering"
}

# ── Configuration File Generators ───────────────────────────────────────────
generate_postgres_init() {
    local out="${CONFIG_DIR}/postgres/init-all-databases.sh"
    mkdir -p "$(dirname "$out")"
    # Double-quoted: POSTGRES_PASSWORD expands NOW at generation time.
    # Inner \$\$ escapes are for the psql DO block's dollar-quoting.
    cat > "$out" <<EOF
#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "\$POSTGRES_USER" --dbname "\$POSTGRES_DB" <<EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_USER}') THEN
      CREATE ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
    END IF;
  END \$\$;
  SELECT 'CREATE DATABASE litellm   OWNER ${POSTGRES_USER}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='litellm')   \gexec
  SELECT 'CREATE DATABASE openwebui OWNER ${POSTGRES_USER}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='openwebui') \gexec
  SELECT 'CREATE DATABASE n8n       OWNER ${POSTGRES_USER}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='n8n')       \gexec
  SELECT 'CREATE DATABASE flowise   OWNER ${POSTGRES_USER}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='flowise')   \gexec
  GRANT ALL PRIVILEGES ON DATABASE litellm   TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE openwebui TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE n8n       TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE flowise   TO ${POSTGRES_USER};
EOSQL
EOF
    chmod +x "$out"
    # postgres container runs as UID 70 — must be able to read this file
    chown 70:"${TENANT_GID:-1001}" "$out"
    log_success "Postgres init script written to ${out}"
}

generate_litellm_config() {
    log_info "Generating LiteLLM configuration..."
    
    # Enhanced Azure validation to prevent restart loops
    local az_config_valid=true
    if [[ -n "${LITELM_AZURE_API_BASE:-}" ]]; then
        if [[ -z "${LITELM_AZURE_API_KEY:-}" ]]; then
            log_warning "Azure API base configured but missing API key - using local models only"
            az_config_valid=false
        elif [[ "${LITELM_AZURE_API_BASE}" == *"test"* ]]; then
            log_warning "Test Azure endpoints detected - disabling Azure models to prevent failures"
            az_config_valid=false
        fi
    fi
    
    cat > "${CONFIG_DIR}/litellm/config.yaml" << EOF
# LiteLLM Configuration - Generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# This file routes LLM requests to appropriate models based on cost/latency

model_list:
  # Local Ollama models (cost-optimized)
EOF
    
    # Add Ollama models dynamically from OLLAMA_MODELS
    [[ -n "${OLLAMA_MODELS:-}" ]] && for m in ${OLLAMA_MODELS//,/ }; do
        cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: ${m}
    litellm_params:
      model: ollama/${m}
      api_base: "http://ollama:11434"
      rpm: 100
EOF
    done
    
    # Only add OpenAI models if API key is provided and not empty
    [[ -n "${OPENAI_API_KEY:-}" && "${OPENAI_API_KEY}" != "" ]] && cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
EOF
    
    # Only add Azure models if configuration is valid and not empty
    if [[ "$az_config_valid" == "true" ]] && [[ -n "${LITELM_AZURE_API_BASE:-}" && "${LITELM_AZURE_API_BASE}" != "" ]] && [[ -n "${LITELM_AZURE_API_KEY:-}" && "${LITELM_AZURE_API_KEY}" != "" ]]; then
        cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: azure/gpt-4
    litellm_params:
      model: azure/gpt-4
      api_base: "${LITELM_AZURE_API_BASE}"
      api_key: os.environ/LITELM_AZURE_API_KEY
      rpm: 10
  - model_name: azure/gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: "${LITELM_AZURE_API_BASE}"
      api_key: os.environ/LITELM_AZURE_API_KEY
      rpm: 20
EOF
    fi
    
    # Only add Groq models if API key is provided and not empty
    [[ -n "${GROQ_API_KEY:-}" && "${GROQ_API_KEY}" != "" ]] && cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: llama3-groq
    litellm_params:
      model: groq/llama3-70b-8192
      api_key: os.environ/GROQ_API_KEY
EOF
    
    # Only add Anthropic models if API key is provided and not empty
    [[ -n "${ANTHROPIC_API_KEY:-}" && "${ANTHROPIC_API_KEY}" != "" ]] && cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
EOF
    
    # Only add Gemini models if API key is provided and not empty
    [[ -n "${GOOGLE_API_KEY:-}" && "${GOOGLE_API_KEY}" != "" ]] && cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: gemini-pro
    litellm_params:
      model: google/gemini-pro
      api_key: os.environ/GOOGLE_API_KEY
EOF
    
    # Only add OpenRouter models if API key is provided and not empty
    [[ -n "${OPENROUTER_API_KEY:-}" && "${OPENROUTER_API_KEY}" != "" ]] && cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  - model_name: openrouter-mixtral
    litellm_params:
      model: openrouter/mistralai/mixtral-8x7b
      api_key: os.environ/OPENROUTER_API_KEY
EOF
    
    cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
litellm_settings:
  drop_params: true
  set_verbose: false
  cache: true
  cache_params:
    type: redis
    host: redis
    port: 6379
    password: os.environ/REDIS_PASSWORD
router_settings:
  routing_strategy: ${LITELLM_ROUTING_STRATEGY:-least-busy}
EOF
    
    # Only add fallbacks for models that are actually configured
    if [[ -n "${OPENAI_API_KEY:-}" && "${OPENAI_API_KEY}" != "" ]] || [[ -n "${GROQ_API_KEY:-}" && "${GROQ_API_KEY}" != "" ]] || [[ -n "${GOOGLE_API_KEY:-}" && "${GOOGLE_API_KEY}" != "" ]] || [[ -n "${OPENROUTER_API_KEY:-}" && "${OPENROUTER_API_KEY}" != "" ]]; then
        # Build fallback list from only configured models
        local external_models=()
        [[ -n "${OPENAI_API_KEY:-}" && "${OPENAI_API_KEY}" != "" ]] && external_models+=("gpt-4o")
        [[ -n "${GROQ_API_KEY:-}" && "${GROQ_API_KEY}" != "" ]] && external_models+=("llama3-groq")
        [[ -n "${GOOGLE_API_KEY:-}" && "${GOOGLE_API_KEY}" != "" ]] && external_models+=("gemini-pro")
        [[ -n "${OPENROUTER_API_KEY:-}" && "${OPENROUTER_API_KEY}" != "" ]] && external_models+=("openrouter-mixtral")

        if [[ ${#external_models[@]} -gt 1 ]]; then
            cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
  fallbacks:
EOF
            for model in "${external_models[@]}"; do
                # Build fallback list = all other external models
                local others=()
                for other in "${external_models[@]}"; do
                    [[ "$other" != "$model" ]] && others+=("\"$other\"")
                done
                local others_str
                others_str=$(IFS=,; echo "${others[*]}")
                cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
    - ${model}: [${others_str}]
EOF
            done
        fi
    fi
    
    cat >> "${CONFIG_DIR}/litellm/config.yaml" <<EOF
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/LITELLM_DATABASE_URL
EOF
    log_success "LiteLLM config written to ${CONFIG_DIR}/litellm/config.yaml"
}

generate_caddyfile() {
    local out="${CONFIG_DIR}/caddy/Caddyfile"
    mkdir -p "$(dirname "$out")"

    # Choose TLS directive once based on USE_LETSENCRYPT
    local tls_line
    if [[ "${USE_LETSENCRYPT:-false}" == "true" ]]; then
        tls_line="tls ${ADMIN_EMAIL}"
    else
        tls_line="tls internal"
    fi

    # Write global block — heredoc closed BEFORE conditional appends
    cat > "$out" <<EOF
{
    admin 0.0.0.0:2019
    email ${ADMIN_EMAIL:-admin@${DOMAIN:-localhost}}
}
EOF

    # Append one block per enabled service — each is a separate cat call
    [[ "${ENABLE_MONITORING:-false}" == "true" ]] && cat >> "$out" <<EOF
grafana.${DOMAIN} {
    ${tls_line}
    reverse_proxy grafana:3000
}
prometheus.${DOMAIN} {
    ${tls_line}
    reverse_proxy prometheus:9090
}
EOF

    [[ "${ENABLE_LITELLM:-false}" == "true" ]] && cat >> "$out" <<EOF
litellm.${DOMAIN} {
    ${tls_line}
    reverse_proxy litellm:4000
}
EOF

    [[ "${ENABLE_OPENWEBUI:-false}" == "true" ]] && cat >> "$out" <<EOF
chat.${DOMAIN} {
    ${tls_line}
    reverse_proxy open-webui:8080
}
EOF

    [[ "${ENABLE_N8N:-false}" == "true" ]] && cat >> "$out" <<EOF
n8n.${DOMAIN} {
    ${tls_line}
    reverse_proxy n8n:5678
}
EOF

    [[ "${ENABLE_FLOWISE:-false}" == "true" ]] && cat >> "$out" <<EOF
flowise.${DOMAIN} {
    ${tls_line}
    reverse_proxy flowise:3000
}
EOF

    [[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] && cat >> "$out" <<EOF
anythingllm.${DOMAIN} {
    ${tls_line}
    reverse_proxy anythingllm:3001
}
EOF

    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] && cat >> "$out" <<EOF
codeserver.${DOMAIN} {
    ${tls_line}
    reverse_proxy codeserver:8443
}
EOF

    # OpenCode - Primary IDE access
    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] && cat >> "$out" <<EOF
opencode.${DOMAIN} {
    ${tls_line}
    reverse_proxy codeserver:8443
}
EOF

    # OpenClaw - routes to Docker service for secure access
    [[ "${ENABLE_OPENCLAW:-false}" == "true" ]] && cat >> "$out" <<EOF
openclaw.${DOMAIN} {
    ${tls_line}
    reverse_proxy openclaw:8443
}
EOF

    log_success "Caddyfile written to ${out}"
}

generate_prometheus_config() {
    [[ "${ENABLE_MONITORING:-false}" == "true" ]] || return 0
    local out="${CONFIG_DIR}/prometheus/prometheus.yml"
    mkdir -p "$(dirname "$out")"
    
    cat > "$out" <<EOF
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']
EOF
    
    [[ "${ENABLE_LITELLM:-false}" == "true" ]] && cat >> "$out" <<EOF
  - job_name: litellm
    static_configs:
      - targets: ['litellm:4000']
    metrics_path: /metrics
EOF
    
    log_success "Prometheus config written to ${out}"
}

generate_codeserver_config() {
    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] || return 0
    local config_dir="${DATA_DIR}/codeserver/.continue"
    mkdir -p "$config_dir"
    chown -R 1000:"${TENANT_GID:-1001}" "$(dirname "$config_dir")"

    cat > "${config_dir}/config.json" <<EOF
{
  "models": [
    {
      "title": "Local (Ollama via LiteLLM)",
      "provider": "openai",
      "model": "${OLLAMA_DEFAULT_MODEL:-llama3.2:1b}",
      "apiBase": "http://litellm:4000/v1",
      "apiKey": "${LITELLM_MASTER_KEY}"
    }
$(
  [[ -n "${OPENAI_API_KEY:-}" ]] && echo "    ,{\"title\":\"GPT-4o (via LiteLLM)\",\"provider\":\"openai\",\"model\":\"gpt-4o\",\"apiBase\":\"http://litellm:4000/v1\",\"apiKey\":\"${LITELLM_MASTER_KEY}\"}" || true
  [[ -n "${GOOGLE_API_KEY:-}" ]] && echo "    ,{\"title\":\"Gemini Pro (via LiteLLM)\",\"provider\":\"openai\",\"model\":\"gemini-pro\",\"apiBase\":\"http://litellm:4000/v1\",\"apiKey\":\"${LITELLM_MASTER_KEY}\"}" || true
  [[ -n "${GROQ_API_KEY:-}" ]]  && echo "    ,{\"title\":\"Llama3 Groq (via LiteLLM)\",\"provider\":\"openai\",\"model\":\"llama3-groq\",\"apiBase\":\"http://litellm:4000/v1\",\"apiKey\":\"${LITELLM_MASTER_KEY}\"}" || true
)
  ],
  "tabAutocompleteModel": {
    "title": "Autocomplete",
    "provider": "openai",
    "model": "${OLLAMA_DEFAULT_MODEL:-llama3.2:1b}",
    "apiBase": "http://litellm:4000/v1",
    "apiKey": "${LITELLM_MASTER_KEY}"
  },
  "embeddingsProvider": {
    "provider": "openai",
    "model": "${OLLAMA_DEFAULT_MODEL:-llama3.2:1b}",
    "apiBase": "http://litellm:4000/v1",
    "apiKey": "${LITELLM_MASTER_KEY}"
  }
}
EOF
    log_success "Continue.dev config written to ${config_dir}/config.json"
}

# Single entry point for all config generation
generate_configs() {
    log_info "Generating all configuration files..."
    generate_postgres_init
    generate_litellm_config
    generate_caddyfile
    generate_prometheus_config
    generate_codeserver_config
    log_success "All configuration files generated"
}

# ── Docker Compose Generator (Zero Hardcoded Values) ───────────────────────
generate_compose() {
    log_info "Generating docker-compose.yml at ${COMPOSE_FILE}..."
    
    cat > "$COMPOSE_FILE" <<'EOF'
networks:
  default:
    name: ai-${TENANT}-net
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  litellm_data:

services:

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    user: "${POSTGRES_UID:-70}:${TENANT_GID:-1001}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${CONFIG_DIR}/postgres/init-all-databases.sh:/docker-entrypoint-initdb.d/init-all-databases.sh:ro
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    user: "${REDIS_UID:-999}:${TENANT_GID:-1001}"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ${DATA_DIR}/redis:/data
    healthcheck:
      test: ["CMD","redis-cli","-a","${REDIS_PASSWORD}","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
EOF

    # Add enabled services dynamically - NO hardcoded values
    [[ "${ENABLE_LITELLM:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  litellm:
    image: ghcr.io/berriai/litellm:main
    restart: unless-stopped
    user: "root"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      DATABASE_URL: ${LITELLM_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
      LITELLM_TELEMETRY: "False"
      PRISMA_DISABLE_WARNINGS: "true"
    volumes:
      - ${CONFIG_DIR}/litellm/config.yaml:/app/config.yaml:ro
      - ${DATA_DIR}/litellm:/root/.cache
    ports:
      - "${PORT_LITELLM:-4000}:4000"
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4000/health/liveliness || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
EOF

    [[ "${ENABLE_OPENWEBUI:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      OPENAI_API_BASE_URL: "http://litellm:4000/v1"
      OPENAI_API_KEY: "${LITELLM_MASTER_KEY}"
      WEBUI_SECRET_KEY: "${JWT_SECRET}"
      # DATABASE_URL removed — open-webui uses SQLite (postgres triggers peewee bug)
      # VECTOR_DB removed — uses built-in Chroma until qdrant is stable
    volumes:
      - ${DATA_DIR}/openwebui:/app/backend/data
    ports:
      - "${PORT_OPENWEBUI:-3000}:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
EOF

    [[ "${ENABLE_OLLAMA:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      OLLAMA_HOST: 0.0.0.0
      # OLLAMA_MODELS removed - volume mount at /root/.ollama controls model storage
    volumes:
      - ${DATA_DIR}/ollama:/root/.ollama
    ports:
      - "${PORT_OLLAMA:-11434}:11434"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # was 60s — model pull takes time on 2-core
EOF

    [[ "${ENABLE_QDRANT:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    volumes:
      - ${DATA_DIR}/qdrant:/qdrant/storage
      - ${DATA_DIR}/qdrant/snapshots:/qdrant/snapshots
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:6333/collections || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s   # was 30s — needs longer on fresh volume
EOF

    [[ "${ENABLE_MONITORING:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    user: "65534:65534"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ${CONFIG_DIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472:472"
    ports:
      - "${PORT_GRAFANA:-3002}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: "https://grafana.${DOMAIN}"
      GF_ANALYTICS_REPORTING_ENABLED: "false"
    volumes:
      - ${DATA_DIR}/grafana/data:/var/lib/grafana
      - ${DATA_DIR}/grafana/logs:/var/log/grafana
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
EOF

    [[ "${ENABLE_N8N:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    depends_on:
      litellm:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      N8N_AI_OPENAI_API_KEY: "${LITELLM_MASTER_KEY}"
      N8N_AI_OPENAI_BASE_URL: "http://litellm:4000/v1"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_HOST: "postgres"
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: "n8n"
      DB_POSTGRESDB_USER: "${POSTGRES_USER}"
      DB_POSTGRESDB_PASSWORD: "${POSTGRES_PASSWORD}"
      N8N_ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
      WEBHOOK_URL: "https://n8n.${DOMAIN}"
    volumes:
      - ${DATA_DIR}/n8n:/home/node/.n8n
    ports:
      - "${PORT_N8N:-5678}:5678"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
EOF

    [[ "${ENABLE_FLOWISE:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  flowise:
    image: flowiseai/flowise:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    depends_on:
      litellm:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: "${LITELLM_MASTER_KEY}"
      OPENAI_API_BASE: "http://litellm:4000/v1"
      DATABASE_PATH: "/root/.flowise"
      FLOWISE_USERNAME: "admin"
      FLOWISE_PASSWORD: "${ADMIN_PASSWORD}"
      SECRETKEY_PATH: "/root/.flowise"
    volumes:
      - ${DATA_DIR}/flowise:/root/.flowise
    ports:
      - "${PORT_FLOWISE:-3001}:3000"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:3000/api/v1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
EOF

    [[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    depends_on:
      litellm:
        condition: service_healthy
    environment:
      LLM_PROVIDER: "openai"
      OPEN_AI_KEY: "${LITELLM_MASTER_KEY}"
      OPEN_AI_BASE_PATH: "http://litellm:4000/v1"
      EMBEDDING_ENGINE: "openai"
      EMBEDDING_BASE_PATH: "http://litellm:4000/v1"
      VECTOR_DB: "${VECTOR_DB_TYPE:-qdrant}"
      QDRANT_ENDPOINT: "http://qdrant:6333"
      STORAGE_DIR: "/app/server/storage"
    volumes:
      - ${DATA_DIR}/anythingllm:/app/server/storage
    ports:
      - "${PORT_ANYTHINGLLM:-3003}:3001"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
EOF

    # Tailscale VPN
    [[ "${ENABLE_TAILSCALE:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    # Removed user: directive - Tailscale needs root for /dev/net/tun access
    volumes:
      - ${DATA_DIR}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_EXTRA_ARGS: "--hostname=${TENANT:-platform}"
    healthcheck:
      test: ["CMD-SHELL","tailscale --socket=\"/tmp/tailscaled.sock\" status | grep -q '@'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF

    # OpenClaw web terminal — Tailscale-gated access
    [[ "${ENABLE_OPENCLAW:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  openclaw:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    environment:
      PUID: "1000"
      PGID: "${TENANT_GID:-1001}"
      PASSWORD: "${ADMIN_PASSWORD}"
      SUDO_PASSWORD: "${ADMIN_PASSWORD}"
      DEFAULT_WORKSPACE: "/mnt/data"
    volumes:
      - ${DATA_DIR}/openclaw:/config
      - /mnt/data:/mnt/data:ro
    ports:
      - "${PORT_OPENCLAW:-18789}:8443"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:8443/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF

    # Code Server - VS Code in browser with Continue.dev extension
    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] && cat >> "$COMPOSE_FILE" <<'EOF'
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    user: "1000:${TENANT_GID:-1001}"
    depends_on:
      litellm:
        condition: service_healthy
    environment:
      PUID: "1000"
      PGID: "${TENANT_GID:-1001}"
      PASSWORD: "${CODESERVER_PASSWORD}"
      SUDO_PASSWORD: "${CODESERVER_PASSWORD}"
      DEFAULT_WORKSPACE: "/mnt/data"
      LITELLM_API_KEY: "${LITELLM_MASTER_KEY}"
      LITELLM_BASE_URL: "http://litellm:4000/v1"
      # Continue.dev extension configuration
      EXTENSIONS_GALLERY: "https://open-vsx.org/vsx-extension-gallery"
      EXTENSIONS: "continuedev.continue"
      # Git repository access
      GIT_REPO: "${GIT_REPO:-/mnt/data/git}"
    volumes:
      - ${DATA_DIR}/codeserver:/config
      - ${DATA_DIR}/codeserver/.continue:/home/abc/.continue:rw
      - /mnt/data:/mnt/data:rw
      - ${DATA_DIR}/git:/mnt/data/git:rw
      - ${TENANT_DIR}/${GITHUB_PROJECT:-github}:/config/workspace
    ports:
      - "${PORT_CODESERVER:-8443}:8443"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:8443/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF

    # Continue.dev - AI-powered development assistant (runs inside Code Server)
    # Note: This is configured as an extension, not a separate service

    # Caddy - always deployed as reverse proxy
    cat >> "$COMPOSE_FILE" <<'EOF'
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ${CONFIG_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${CONFIG_DIR}/caddy/data:/data
      - ${CONFIG_DIR}/caddy/config:/config
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:2019/metrics > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
EOF

    log_success "docker-compose.yml generated at ${COMPOSE_FILE}"
}

# ── Service Lifecycle Functions ───────────────────────────────────────────────
deploy_service() {
    local svc="$1"
    local logfile="${LOGS_DIR}/deploy-$(date +%Y%m%d).log"
    log_info "Deploying ${svc}..."
    
    if docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d "$svc" \
            >> "$logfile" 2>&1; then
        log_success "${svc} deployed"
    else
        log_error "${svc} failed — last 20 lines from ${logfile}:"
        tail -20 "$logfile" | sed 's/^/  │ /' || true
        return 0   # non-fatal: log and continue
    fi
}

stop_service() {
    local svc="$1"
    docker compose -f "$COMPOSE_FILE" stop "$svc" \
        && log_success "${svc} stopped" \
        || log_warning "${svc} was not running"
}

wait_for_healthy() {
    local svc="$1"
    local max_wait="${2:-120}"
    local elapsed=0
    log_info "Waiting for ${svc} to be healthy (max ${max_wait}s)..."
    until [[ "$(docker compose -f "$COMPOSE_FILE" ps --format "{{.Health}}" "$svc" 2>/dev/null)" == "healthy" ]]; do
        elapsed=$((elapsed + 5))
        if [[ $elapsed -ge $max_wait ]]; then
            log_warning "${svc} not healthy after ${max_wait}s — proceeding anyway"
            return 0
        fi
        log_info "  ${svc} starting... (${elapsed}s/${max_wait}s)"
        sleep 5
    done
    log_success "${svc} is healthy"
}

reconfigure_service() {
    local svc="$1"
    log_info "Reconfiguring ${svc}..."
    generate_configs
    generate_compose
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" \
        up -d --force-recreate "$svc" \
        >> "${LOGS_DIR}/deploy-$(date +%Y%m%d).log" 2>&1
    log_success "${svc} reconfigured"
}

enable_service() {
    local svc="$1"
    local flag="ENABLE_$(echo "$svc" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
    log_info "Enabling ${svc} (sets ${flag}=true in .env)..."
    grep -q "^${flag}=" "$ENV_FILE" \
        && sed -i "s|^${flag}=.*|${flag}=true|" "$ENV_FILE" \
        || echo "${flag}=true" >> "$ENV_FILE"
    generate_configs
    generate_compose
    deploy_service "$svc"
    log_success "${svc} enabled and deployed"
}

disable_service() {
    local svc="$1"
    local flag="ENABLE_$(echo "$svc" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
    log_info "Disabling ${svc}..."
    stop_service "$svc"
    grep -q "^${flag}=" "$ENV_FILE" \
        && sed -i "s|^${flag}=.*|${flag}=false|" "$ENV_FILE" \
        || echo "${flag}=false" >> "$ENV_FILE"
    log_success "${svc} stopped and disabled"
}

# ── Service Detection ─────────────────────────────────────────────────────────────
service_is_enabled() {
    local svc="$1"
    case "$svc" in
        litellm)   [[ "${ENABLE_LITELLM:-false}"   == "true" ]] ;;
        ollama)    [[ "${ENABLE_OLLAMA:-false}"    == "true" ]] ;;
        open-webui)[[ "${ENABLE_OPENWEBUI:-false}" == "true" ]] ;;
        qdrant)    [[ "${ENABLE_QDRANT:-false}"    == "true" ]] ;;
        n8n)       [[ "${ENABLE_N8N:-false}"       == "true" ]] ;;
        flowise)   [[ "${ENABLE_FLOWISE:-false}"   == "true" ]] ;;
        anythingllm)[[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] ;;
        codeserver) [[ "${ENABLE_CODESERVER:-false}" == "true" ]] ;;
        openclaw)  [[ "${ENABLE_OPENCLAW:-false}"  == "true" ]] ;;
        prometheus|grafana) [[ "${ENABLE_MONITORING:-false}" == "true" ]] ;;
        *) return 1 ;;
    esac
}

provision_databases() {
    log_info "Provisioning per-service databases..."
    
    local max_wait=60
    local elapsed=0
    
    # Wait for postgres to accept connections
    until docker compose -f "$COMPOSE_FILE" exec -T postgres \
        pg_isready -U "${POSTGRES_USER}" -q 2>/dev/null; do
        elapsed=$((elapsed + 5))
        if [[ $elapsed -ge $max_wait ]]; then
            log_error "PostgreSQL not ready after ${max_wait}s"
            return 1
        fi
        log_info "Waiting for postgres... (${elapsed}s)"
        sleep 5
    done
    
    log_success "PostgreSQL is ready"
    
    # Create per-service databases (idempotent — safe to re-run)
    local databases=("litellm" "openwebui" "n8n" "flowise")
    for db in "${databases[@]}"; do
        local exists
        exists=$(docker compose -f "$COMPOSE_FILE" exec -T postgres \
            psql -U "${POSTGRES_USER}" -tAc \
            "SELECT 1 FROM pg_database WHERE datname='${db}'" 2>/dev/null || echo "")
        
        if [[ "$exists" == "1" ]]; then
            log_info "Database '${db}' already exists — skipping"
        else
            log_info "Creating database '${db}'..."
            docker compose -f "$COMPOSE_FILE" exec -T postgres \
                psql -U "${POSTGRES_USER}" \
                -c "CREATE DATABASE \"${db}\" OWNER \"${POSTGRES_USER}\";" \
                >> "${LOGS_DIR}/deploy-$(date +%Y%m%d).log" 2>&1 \
                && log_success "Database '${db}' created" \
                || log_warning "Could not create '${db}' — may already exist"
        fi
    done
    
    log_success "Database provisioning complete"
}

# ── Log Management Functions ───────────────────────────────────────────────────
log_enable() {
    local svc="$1"
    log_info "Enabling log streaming for ${svc}..."
    local logfile="${LOGS_DIR}/${svc}-$(date +%Y%m%d).log"
    
    # Kill any existing log stream for this service
    pkill -f "docker compose.*logs.*${svc}" 2>/dev/null || true
    
    # Start new log stream in background
    docker compose -f "$COMPOSE_FILE" logs -f "$svc" \
        >> "$logfile" 2>&1 &
    
    local pid=$!
    echo "$pid" > "${LOGS_DIR}/.${svc}.pid"
    
    log_success "Log streaming enabled for ${svc} → ${logfile}"
}

log_disable() {
    local svc="$1"
    log_info "Disabling log streaming for ${svc}..."
    
    # Kill by PID file if exists
    local pidfile="${LOGS_DIR}/.${svc}.pid"
    if [[ -f "$pidfile" ]]; then
        local pid=$(cat "$pidfile")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            log_success "Log stream stopped for ${svc} (PID $pid)"
        fi
        rm -f "$pidfile"
    fi
    
    # Fallback: kill by process name
    pkill -f "docker compose.*logs.*${svc}" 2>/dev/null || true
    
    log_success "Log streaming disabled for ${svc}"
}

log_rotate() {
    local svc="${1:-}"
    local keep_days="${2:-7}"
    
    if [[ -n "$svc" ]]; then
        log_info "Rotating logs for ${svc} (keep ${keep_days} days)..."
        find "$LOGS_DIR" -name "${svc}-*.log" -mtime +${keep_days} -delete
    else
        log_info "Rotating all service logs (keep ${keep_days} days)..."
        find "$LOGS_DIR" -name "*-*.log" -mtime +${keep_days} -delete
    fi
    
    log_success "Log rotation completed"
}

log_cleanup() {
    local keep_days="${1:-30}"
    log_info "Cleaning up old logs (keep ${keep_days} days)..."
    
    # Clean old log files
    find "$LOGS_DIR" -name "*.log" -mtime +${keep_days} -delete
    find "$LOGS_DIR" -name "*.log.*" -mtime +${keep_days} -delete
    
    # Clean old PID files
    find "$LOGS_DIR" -name ".*.pid" -mtime +1 -delete
    
    log_success "Log cleanup completed"
}

# ── Health Dashboard Functions ───────────────────────────────────────────────
_check_http() {
    local name="$1" url="$2"
    if curl -sf --max-time 5 "$url" > /dev/null 2>&1; then
        printf "  ${GREEN}🟢 %-22s${NC} %s\n" "$name" "$url"
    else
        printf "  ${RED}🔴 %-22s${NC} %s\n" "$name" "$url"
    fi
}

_check_https() {
    local name="$1" url="$2"
    if curl -sfk --max-time 5 "$url" > /dev/null 2>&1; then
        printf "  ${GREEN}🟢 %-22s${NC} %s\n" "$name" "$url"
    else
        printf "  ${RED}🔴 %-22s${NC} %s\n" "$name" "$url"
    fi
}

_check_cmd() {
    local name="$1"; shift
    if "$@" > /dev/null 2>&1; then
        printf "  ${GREEN}🟢 %-22s${NC} %s\n" "$name" "$(docker compose -f "$COMPOSE_FILE" ps --format "{{.Status}}" "$name" 2>/dev/null | head -1)"
    else
        printf "  ${RED}🔴 %-22s${NC} %s\n" "$name" "not responding"
    fi
}

health_dashboard() {
    set -a; source "$ENV_FILE"; set +a
    local ts ip=""
    ts=$(date '+%Y-%m-%d %H:%M:%S')

    # Tailscale IP - use reliable tailscale ip -4 method
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "tailscale"; then
        ip=$(docker compose -f "$COMPOSE_FILE" exec -T tailscale \
            tailscale --socket="/tmp/tailscaled.sock" ip -4 2>/dev/null \
            | tr -d ' \n' || true)
        # Fallback: read from .env if already stored
        [[ -z "$ip" ]] && ip=$(grep "^TAILSCALE_IP=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 || true)
    else
        ip="NOT CONNECTED"
    fi

    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║  AI PLATFORM HEALTH DASHBOARD — ${ts}    ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    printf "  %-14s %s\n" "Domain:"       "https://${DOMAIN}"
    printf "  %-14s %s\n" "Tailscale IP:" "${ip:-NOT CONNECTED}"
    if [[ "${ENABLE_OPENCLAW:-false}" == "true" && -n "$ip" ]]; then
        printf "  %-14s %s\n" "OpenClaw:" "https://${ip}:${PORT_OPENCLAW:-18789} (Tailscale only)"
    fi
    printf "  %-14s %s\n" "Tenant:"       "${TENANT}"
    printf "  %-14s %s\n" "Data:"         "${TENANT_DIR}"
    echo ""
    echo -e "  ${BOLD}Infrastructure${NC}"
    _check_cmd  "postgres"   docker compose -f "$COMPOSE_FILE" exec -T postgres \
                             pg_isready -U "${POSTGRES_USER}" -q
    _check_cmd  "redis"      docker compose -f "$COMPOSE_FILE" exec -T redis \
                             redis-cli -a "${REDIS_PASSWORD}" ping
    [[ "${ENABLE_QDRANT:-false}"    == "true" ]] && \
        _check_http "qdrant"     "http://localhost:${PORT_QDRANT:-6333}/collections"
    echo ""
    echo -e "  ${BOLD}Monitoring${NC}"
    [[ "${ENABLE_MONITORING:-false}" == "true" ]] && {
        _check_http "prometheus" "http://localhost:${PORT_PROMETHEUS:-9090}/-/healthy"
        _check_http "grafana"    "http://localhost:${PORT_GRAFANA:-3002}/api/health"
    }
    _check_http "caddy"      "http://localhost:2019/metrics"
    echo ""
    echo -e "  ${BOLD}AI Services${NC}"
    [[ "${ENABLE_LITELLM:-false}"    == "true" ]] && \
        _check_http "litellm"    "http://localhost:${PORT_LITELLM:-4000}/health/liveliness"
    [[ "${ENABLE_OLLAMA:-false}"     == "true" ]] && \
        _check_http "ollama"     "http://localhost:11434/"
    echo ""
    echo -e "  ${BOLD}Development Environment${NC}"
    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] && \
        _check_http "codeserver"     "http://localhost:${PORT_CODESERVER:-8443}/"
    echo ""
    echo -e "  ${BOLD}Web Services (all routed via LiteLLM)${NC}"
    [[ "${ENABLE_OPENWEBUI:-false}"  == "true" ]] && \
        _check_http "open-webui"     "http://localhost:${PORT_OPENWEBUI:-3000}/"
    [[ "${ENABLE_N8N:-false}"        == "true" ]] && \
        _check_http "n8n"            "http://localhost:${PORT_N8N:-5678}/healthz"
    [[ "${ENABLE_FLOWISE:-false}"    == "true" ]] && \
        _check_http "flowise"        "http://localhost:${PORT_FLOWISE:-3001}/"
    [[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] && \
        _check_http "anythingllm"    "http://localhost:${PORT_ANYTHINGLLM:-3003}/"
    [[ "${ENABLE_OPENCLAW:-false}"  == "true" ]] && \
        _check_https "openclaw"      "https://openclaw.${DOMAIN}/"
    echo ""
    echo -e "  ${BOLD}Quick Tests${NC}"
    echo -e "  LiteLLM models:"
    echo -e "    curl -s http://localhost:${PORT_LITELLM:-4000}/v1/models \\"
    echo -e "      -H 'Authorization: Bearer \${LITELLM_MASTER_KEY}' | jq '.data[].id'"
    echo ""
    echo -e "  ${BOLD}🌐 Access URLs${NC}"
    printf "  %-26s %s\n" "Chat (OpenWebUI):"     "https://chat.${DOMAIN}"
    [[ "${ENABLE_LITELLM:-false}"    == "true" ]] && printf "  %-26s %s\n" "LiteLLM API:"        "https://litellm.${DOMAIN}"
    [[ "${ENABLE_N8N:-false}"        == "true" ]] && printf "  %-26s %s\n" "n8n Automation:"     "https://n8n.${DOMAIN}"
    [[ "${ENABLE_FLOWISE:-false}"    == "true" ]] && printf "  %-26s %s\n" "Flowise:"            "https://flowise.${DOMAIN}"
    [[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] && printf "  %-26s %s\n" "AnythingLLM:"       "https://anythingllm.${DOMAIN}"
    [[ "${ENABLE_CODESERVER:-false}" == "true" ]] && printf "  %-26s %s\n" "OpenCode IDE:"       "https://opencode.${DOMAIN}"
    [[ "${ENABLE_MONITORING:-false}" == "true" ]] && {
        printf "  %-26s %s\n" "Grafana:"           "https://grafana.${DOMAIN}"
        printf "  %-26s %s\n" "Prometheus:"        "https://prometheus.${DOMAIN}"
    }
    [[ "${ENABLE_OPENCLAW:-false}"  == "true" ]] && \
        printf "  %-26s %s\n" "OpenClaw (Tailscale):" "https://${ip:-<tailscale-ip>}:${PORT_OPENCLAW:-18789}"
    echo ""
    echo -e "  ${BOLD}⚡ LiteLLM Quick Test${NC}"
    echo -e "    curl -s https://litellm.${DOMAIN}/v1/models \\"
    echo -e "      -H 'Authorization: Bearer \${LITELLM_MASTER_KEY}' | jq '.data[].id'"
    echo ""
    log_write INFO "Health dashboard printed at ${ts}"
}

# ── External Integration Functions ───────────────────────────────────────────
configure_tailscale() {
    [[ -n "${TAILSCALE_AUTH_KEY:-}" ]] || { 
        log_info "TAILSCALE_AUTH_KEY not set — skipping"; 
        return 0; 
    }
    
    # Check if tailscale service exists in compose
    if ! docker compose -f "$COMPOSE_FILE" config | grep -q "tailscale:"; then
        log_warning "Tailscale service not found in compose configuration"
        return 1
    fi
    
    log_info "Configuring Tailscale..."
    
    # Deploy tailscale if not running
    if ! docker ps --format '{{.Names}}' | grep -q tailscale; then
        deploy_service tailscale
        sleep 10  # Give tailscale time to start
    fi
    
    # Authenticate (only if not already authenticated)
    if ! docker compose -f "$COMPOSE_FILE" exec -T tailscale \
        tailscale --socket="/tmp/tailscaled.sock" status | grep -q "Logged in as"; then
        docker compose -f "$COMPOSE_FILE" exec -T tailscale \
            tailscale --socket="/tmp/tailscaled.sock" up --authkey="${TAILSCALE_AUTH_KEY}" --hostname="${TENANT:-platform}" --accept-dns=false || {
            log_error "Tailscale authentication failed"
            return 1
        }
    fi
    
    sleep 5
    local ip
    ip=$(docker compose -f "$COMPOSE_FILE" exec -T tailscale \
        tailscale --socket="/tmp/tailscaled.sock" ip -4 2>/dev/null | tr -d ' \n' || true)
    
    if [[ -n "$ip" ]]; then
        # Update .env with Tailscale IP
        grep -q "^TAILSCALE_IP=" "$ENV_FILE" \
            && sed -i "s|^TAILSCALE_IP=.*|TAILSCALE_IP=${ip}|" "$ENV_FILE" \
            || echo "TAILSCALE_IP=${ip}" >> "$ENV_FILE"
        log_success "Tailscale configured with IP: ${ip}"
    else
        log_warning "Could not get Tailscale IP"
    fi
}

setup_gdrive_rclone() {
    [[ -n "${GDRIVE_CLIENT_ID:-}" ]] || { 
        log_info "GDrive not configured — skipping"; 
        return 0; 
    }
    
    log_info "Configuring rclone GDrive remote..."
    
    # Check if rclone is installed
    if ! command -v rclone &> /dev/null; then
        log_info "Installing rclone..."
        curl -fsSL https://rclone.org/install.sh | bash
    fi
    
    # Configure GDrive remote
    rclone config create gdrive drive \
        client_id="${GDRIVE_CLIENT_ID}" \
        client_secret="${GDRIVE_CLIENT_SECRET}" \
        token="{\"access_token\":\"\",\"token_type\":\"Bearer\",\"refresh_token\":\"${GDRIVE_REFRESH_TOKEN}\",\"expiry\":\"\"}" || {
        log_error "Failed to configure rclone GDrive remote"
        return 1
    }
    
    log_success "rclone GDrive configured"
}

create_ingestion_systemd() {
    [[ -n "${GDRIVE_CLIENT_ID:-}" ]] || return 0

    log_info "Installing gdrive-sync systemd timer..."

    local gdrive_dir="${DATA_DIR}/gdrive"
    mkdir -p "$gdrive_dir"
    chown "${TENANT_UID:-1001}:${TENANT_GID:-1001}" "$gdrive_dir"

    # Create systemd service — syncs then optionally triggers ingestion
    cat > /etc/systemd/system/gdrive-sync-${TENANT}.service <<EOF
[Unit]
Description=AI Platform GDrive sync for ${TENANT}
After=docker.service network.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'rclone sync gdrive: ${DATA_DIR}/gdrive/ --log-file ${LOGS_DIR}/rclone-sync.log'
User=root
EOF

    # Create systemd timer — runs every 4 minutes
    cat > /etc/systemd/system/gdrive-sync-${TENANT}.timer <<EOF
[Unit]
Description=GDrive Sync Timer for ${TENANT}

[Timer]
OnCalendar=*:0/4
Persistent=true

[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now gdrive-sync-${TENANT}.timer

    log_success "gdrive-sync-${TENANT} timer installed — syncing to ${DATA_DIR}/gdrive/"
}

# ── Service Recovery ─────────────────────────────────────────────────────
recover_services() {
    log_info "Recovering failed services..."
    
    # Restart LiteLLM with configuration validation
    if [[ "${ENABLE_LITELLM:-false}" == "true" ]]; then
        log_info "Restarting LiteLLM with configuration validation..."
        docker compose -f "$COMPOSE_FILE" restart litellm
        sleep 10
    fi
    
    # Restart OpenWebUI with environment validation
    if [[ "${ENABLE_OPENWEBUI:-false}" == "true" ]]; then
        log_info "Restarting OpenWebUI with environment validation..."
        docker compose -f "$COMPOSE_FILE" restart open-webui
        sleep 15
    fi
    
    log_success "Service recovery completed"
}

# ── GDrive → Qdrant Ingestion ─────────────────────────────────────────────────
ingest_gdrive_to_qdrant() {
    [[ -n "${GDRIVE_CLIENT_ID:-}" ]] || {
        log_warning "GDrive not configured — run: $0 gdrive first"
        return 1
    }
    [[ "${ENABLE_ANYTHINGLLM:-false}" == "true" ]] || {
        log_warning "AnythingLLM not enabled — enable it first: $0 enable anythingllm"
        return 1
    }

    log_info "Starting GDrive → Qdrant ingestion via AnythingLLM..."

    # 1. Sync gdrive to local
    log_info "Syncing GDrive to ${DATA_DIR}/gdrive/ ..."
    mkdir -p "${DATA_DIR}/gdrive"
    rclone sync gdrive: "${DATA_DIR}/gdrive/" \
        --log-file "${LOGS_DIR}/rclone-sync.log" \
        && log_success "GDrive sync complete" \
        || { log_error "GDrive sync failed — check ${LOGS_DIR}/rclone-sync.log"; return 1; }

    # 2. Get AnythingLLM API key from .env
    local atllm_key="${ANYTHINGLLM_API_KEY:-${LITELLM_MASTER_KEY}}"
    local atllm_url="http://localhost:${PORT_ANYTHINGLLM:-3003}"

    # 3. Upload each file to AnythingLLM via its upload API
    log_info "Uploading documents to AnythingLLM for embedding into Qdrant..."
    local count=0 failed=0
    while IFS= read -r -d '' file; do
        local filename
        filename="$(basename "$file")"
        # AnythingLLM accepts file upload via /api/v1/document/upload
        if curl -sf -X POST \
            "${atllm_url}/api/v1/document/upload" \
            -H "Authorization: Bearer ${atllm_key}" \
            -F "file=@${file}" \
            > /dev/null 2>&1; then
            count=$((count + 1))
        else
            log_warning "Failed to upload: ${filename}"
            failed=$((failed + 1))
        fi
    done < <(find "${DATA_DIR}/gdrive" -type f \( \
        -name "*.pdf" -o -name "*.txt" -o -name "*.md" \
        -o -name "*.docx" -o -name "*.csv" \) -print0)

    log_success "GDrive ingestion complete — ${count} files embedded, ${failed} failed"
    log_info "Verify collections: curl -s http://localhost:${PORT_QDRANT:-6333}/collections | jq"
}

# ── CLI Dispatcher (Only runs when script executed directly) ──────────────────
(return 0 2>/dev/null) && return   # sourced - export functions and stop here

main() {
    local tenant="${1:-help}"
    [[ "$tenant" == "help" ]] && {
        echo "Usage: $0 <tenant> <command> [service]"
        echo ""
        echo "Tenants:"
        ls -1 /mnt/data/ 2>/dev/null | sed 's/^/  /' || echo "  (none found)"
        echo ""
        echo "Commands:"
        echo "  Deployment:    deploy <svc>  stop <svc>  restart <svc>  deploy-all  stop-all"
        echo "  Configuration: generate  compose  dirs"
        echo "  Health:        health  status  logs [svc]  logs-on <svc>  logs-off <svc>"
        echo "  Logging:       logs-rotate [svc] [days]  logs-cleanup [days]"
        echo "  Recovery:      recover"
        echo "  Wiring:        tailscale  gdrive  gdrive-ingest"
        echo "  Lifecycle:     enable <svc>  disable <svc>  reconfigure <svc>"
        echo ""
        return 1
    }
    
    # Set TENANT and load environment
    export TENANT="$tenant"
    TENANT_DIR="/mnt/data/${TENANT}"
    CONFIG_DIR="${TENANT_DIR}/configs"
    DATA_DIR="${TENANT_DIR}/data"
    LOGS_DIR="${TENANT_DIR}/logs"
    COMPOSE_FILE="${TENANT_DIR}/docker-compose.yml"
    ENV_FILE="${TENANT_DIR}/.env"
    
    # Load environment variables
    [[ -f "$ENV_FILE" ]] || {
        echo "ERROR: Environment file not found: $ENV_FILE"
        echo "Run script 1 first to create it"
        return 1
    }
    set -a
    source "$ENV_FILE"
    set +a
    
    local cmd="${2:-help}"
    shift 2 || true
    case "$cmd" in
        # ── Deployment ──────────────────────────────────────────────
        deploy)         deploy_service "${1:?usage: deploy <service>}" ;;
        deploy-all)     bash "$(dirname "$0")/2-deploy-services.sh" ;;
        stop)           stop_service   "${1:?usage: stop <service>}" ;;
        stop-all)       docker compose -f "$COMPOSE_FILE" down ;;
        restart)        reconfigure_service "${1:?usage: restart <service>}" ;;

        # ── Configuration ────────────────────────────────────────────
        generate)       generate_configs ;;
        compose)        generate_compose ;;
        dirs)           prepare_directories ;;
        env)            echo "Re-run script 1 to regenerate .env safely" ;;

        # ── Health & Monitoring ──────────────────────────────────────
        health)         health_dashboard ;;
        status)         docker compose -f "$COMPOSE_FILE" ps ;;
        logs)           docker compose -f "$COMPOSE_FILE" logs --tail=50 "${1:-}" ;;
        logs-on)        log_enable  "${1:?usage: logs-on <service>}" ;;
        logs-off)       log_disable "${1:?usage: logs-off <service>}" ;;

        # ── External Wiring ──────────────────────────────────────────
        tailscale)      configure_tailscale ;;
        gdrive)         setup_gdrive_rclone && create_ingestion_systemd ;;
        gdrive-ingest)  ingest_gdrive_to_qdrant ;;
        logs-rotate)    log_rotate "${1:-}" "${2:-7}" ;;
        logs-cleanup)   log_cleanup "${1:-30}" ;;

        # ── Service Recovery ───────────────────────────────────────
        recover)        recover_services ;;

        # ── Service Reconfiguration ──────────────────────────────────
        reconfigure)    reconfigure_service "${1:?usage: reconfigure <service>}" ;;
        enable)         enable_service  "${1:?usage: enable <service>}" ;;
        disable)        disable_service "${1:?usage: disable <service>}" ;;
        update)         update_service  "${1:?usage: update <service>}" ;;
        upgrade)        upgrade_service "${1:?usage: upgrade <service>}" ;;

        # ── Help ─────────────────────────────────────────────────────
        help|*)
            echo ""
            echo "Usage: $0 <command> [service]"
            echo ""
            echo "  Deployment:    deploy <svc>  stop <svc>  restart <svc>  deploy-all  stop-all"
            echo "  Configuration: generate  compose  dirs"
            echo "  Health:        health  status  logs [svc]  logs-on <svc>  logs-off <svc>"
            echo "  Logging:       logs-rotate [svc] [days]  logs-cleanup [days]"
            echo "  Wiring:        tailscale  gdrive  gdrive-ingest"
            echo "  Lifecycle:     enable <svc>  disable <svc>  reconfigure <svc>"
            echo ""
            ;;
    esac
}

main "$@"
