#!/bin/bash

echo "=== Current Structure ==="
echo ""
echo "Main directory:"
ls -la ~/ai-platform-installer/*.sh 2>/dev/null || echo "No scripts found"
echo ""
echo "Configs directory:"
ls -la ~/ai-platform-installer/configs/ 2>/dev/null || echo "No configs directory"
echo ""
echo "Signal config:"
ls -la ~/ai-platform-installer/configs/signal/ 2>/dev/null || echo "No signal config"
echo ""
echo "Signal docker-compose:"
cat ~/ai-platform-installer/configs/signal/docker-compose.yml 2>/dev/null || echo "No signal docker-compose.yml"
echo ""
echo "Current Signal containers:"
docker ps -a --filter "name=signal" --format "table {{.Names}}\t{{.Status}}"
echo ""

