# =============================================================================
# AI Platform - Shared Configuration Constants
# =============================================================================
# This file is sourced by all scripts to prevent configuration drift
# DO NOT EDIT MANUALLY - Generated by script 1
# =============================================================================

# Platform Paths (canonical source)
DATA_DIR="${BASE_DIR}"
COMPOSE_FILE="${BASE_DIR}/config/docker-compose.yml"
CONFIGURED_DIR="${BASE_DIR}/.configured"
LOG_DIR="${BASE_DIR}/logs"

# Docker Network
DOCKER_NETWORK="${TENANT_ID}-network"

# Service Ports (canonical source)
OLLAMA_PORT="${OLLAMA_PORT:-11434}"
OPENWEBUI_PORT="${OPENWEBUI_PORT:-3000}"
N8N_PORT="${N8N_PORT:-5678}"
QDRANT_PORT="${QDRANT_PORT:-6333}"
LITELLM_PORT="${LITELLM_PORT:-4000}"
CADDY_HTTP_PORT="${CADDY_HTTP_PORT:-80}"
CADDY_HTTPS_PORT="${CADDY_HTTPS_PORT:-443}"

# Service URLs (derived)
OLLAMA_URL="http://localhost:${OLLAMA_PORT}"
OPENWEBUI_URL="http://localhost:${OPENWEBUI_PORT}"
N8N_URL="http://localhost:${N8N_PORT}"
QDRANT_URL="http://localhost:${QDRANT_PORT}"
LITELLM_URL="http://localhost:${LITELLM_PORT}"

# Platform Identity
TENANT_PREFIX="${TENANT_ID}"
PLATFORM_USER="$(whoami)"
PUID="$(id -u)"
PGID="$(id -g)"
